<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */

$viewModel = $block->getData('viewModelForOrderHistory');
$ticketViewModel = $block->getData('viewModelCancelReturn');
$orderDataViewModel = $block->getData('viewModelForOrderData');

$returnReasonData = $viewModel->getReturnReasonData();
$storeCode = $viewModel->getStoreCode();
$reasonData = $viewModel->getReasonData();
$storeUrl = $orderDataViewModel->getStoreUrl();
?>
<script>
    var langCode = '<?= $block->escapeJs($storeCode) ?>';
</script>
<div class="request-button">
    <button id="request-btn" class="primary action request-btn">
        <?= /* @noEscape */ __('Returns & Cancelation'); ?>
    </button>
</div>
<div id="orders-modal" class="block block-dashboard-orders" style="display:none;">
    <?php $_orders = $block->getOrders(); ?>
    <?php $count = count($_orders); ?>
    <div class="block-content">
        <?= $block->getChildHtml() ?>
        <?php if ($count > 0) : ?>
            <div class="orders-recent">
                <?php foreach ($_orders as $_order) : ?>
                    <?php $realOrderId = $_order->getIncrementId();
                    $isCancellable = $ticketViewModel->isTicketsCancelReturnOrder($_order, 'Cancel');
                    $isReturnable = $ticketViewModel->isTicketsCancelReturnOrder($_order, 'Return');
                    $currencySymbol = $_order->getOrderCurrency()->getCurrencySymbol();
                    $orderId = $_order->getIncrementId();
                    $orderOriginalId = $_order->getId();
                    $customerEmail = $_order->getCustomerEmail();
                    $customerPhone = $_order->getShippingAddress()->getTelephone();
                    ?>
                    <?php $orderStatus = $viewModel->getOrderStatusList($_order); ?>
                    <div class="orders-recent-items">
                        <p class="col id"><?= $block->escapeHtml(__('Order ID:')) ?>
                            <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                        </p>
                        <div class="orders-recent-details">
                            <div data-th="<?= $block->escapeHtml(__('items')) ?>" class="col items">
                                <?php foreach ($_order->getAllVisibleItems() as $item): ?>
                                    <?php
                                    $isItemCancelled = $ticketViewModel->isTicketsCancelReturnOrderItem($item->getSku(), $orderId, 'Cancel');
                                    $isItemReturned = $ticketViewModel->isTicketsCancelReturnOrderItem($item->getSku(), $orderId, 'Return');
                                    $orderItemIds = $_order->getRealOrderId() . '-' . $item->getItemId();
                                    $rowTotal = (float)$item->getRowTotal();
                                    $discount = (float)$item->getDiscountAmount();
                                    $total = (float)$rowTotal - $discount;
                                    $refundNote = "You are eligible for a refund of $currencySymbol$total excluding discount amount of $currencySymbol$discount";
                                    $rawSku = $item->getSku();
                                    $productName = $item->getName();
                                    $sku = strtolower($rawSku);
                                    $sku = preg_replace('/\s+/', '-', $sku);
                                    ?>
                                    <div class="item"
                                         id="order-item-id-<?= /* @noEscape */ $item->getItemId(); ?>"
                                         data-increment-id="<?= /* @noEscape */ $_order->getRealOrderId() ?>"
                                         data-order-id="<?= /* @noEscape */ $orderOriginalId ?>"
                                         data-sku="<?= /* @noEscape */ $sku; ?>"
                                    >
                                        <div class="product-img">
                                            <img alt="product-image"
                                                 src="<?= /* @noEscape */ $viewModel->getProductImage($item->getProductId()); ?>"
                                                 class="product-image-element"
                                            >
                                        </div>
                                        <div class="product-info">
                                            <p class="date"><?= $block->escapeHtml(__('Order Date')) ?>:
                                                <?= $block->escapeHtml($viewModel->formateOrderDate($_order->getCreatedAt())) ?>
                                            </p>
                                            <h3 class="product-name"><?= /* @noEscape */ $productName; ?></h3>
                                            <p class="product-sku"><?= /* @noEscape */ $block->escapeHtml(__('SKU')) ?>: <?= /* @noEscape */ $item->getSku(); ?></p>
                                            <p class="product-option">
                                                <?php foreach ($viewModel->getSelectedOptions($item) as $options): ?>
                                                    <span class="product-value">
                                                <?= /* @noEscape */ $options['value']; ?>-
                                            </span>
                                                <?php endforeach; ?>
                                                <span class="product-price"><?= /* @noEscape */ $viewModel->formatePrice($item->getRowTotal()); ?></span>
                                            </p>
                                            <td class="col return order-cancel" data-th="<?= $block->escapeHtmlAttr(__('Return')) ?>">
                                                <?php if ($_order->canCancel()): ?>
                                                    <?php if ($isItemCancelled || $isItemReturned): ?>
                                                        <span class="order-request-pending">
                                                <?= $block->escapeHtml(__('Request Pending')) ?>
                                            </span>
                                                    <?php else : ?>
                                                        <div id="item-can-return-<?= $block->escapeHtmlAttr($item->getItemId()) ?>"
                                                             class="show-item-<?= $block->escapeHtmlAttr($sku) ?>" style="display:none">
                                                            <div class="modal-content">
                                                                <p><?= $block->escapeHtml('Return Item: ' . $productName) ?></p>
                                                                <div id="result-<?= $block->escapeHtmlAttr($sku) ?>"></div>
                                                                <div id="loader-<?= $block->escapeHtmlAttr($sku) ?>" style="display:none;">
                                                                    <?= $block->escapeHtml(__('loading')) ?>
                                                                </div>
                                                                <div class="form-data">
                                                                    <div id="order-refund-details_item-<?= $block->escapeHtmlAttr($item->getItemId()) ?>">
                                                                <span id="order-refund-amount_item-<?= $block->escapeHtmlAttr($item->getItemId()) ?>">
                                                                    <?= $block->escapeHtml($refundNote) ?>
                                                                </span>
                                                                    </div>
                                                                    <?php if (!empty($returnReasonData)): ?>
                                                                        <label><?= $block->escapeHtml(__('Select Reason')) ?></label>
                                                                        <select id="order-return-reason-<?= $block->escapeHtmlAttr($orderItemIds) ?>"
                                                                                name="order-return-reason">
                                                                            <option value=""><?= $block->escapeHtml(__('Reason to return')) ?></option>
                                                                            <?php foreach ($returnReasonData as $reason): ?>
                                                                                <option value="<?= $block->escapeHtmlAttr($reason['reason_data']) ?>">
                                                                                    <?= $block->escapeHtml($reason['reason_data']) ?>
                                                                                </option>
                                                                            <?php endforeach; ?>
                                                                        </select>
                                                                    <?php endif; ?>
                                                                    <input class="order-return-submit-item"
                                                                           id="order-return-submit-<?= $block->escapeHtmlAttr($orderItemIds) ?>"
                                                                           data-item-id="<?= /* @noEscape */ $item->getItemId(); ?>"
                                                                           type="button"
                                                                           value="Send"
                                                                           name="submit">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="show-item-<?= /* @noEscape */ $item->getItemId(); ?>" style="display:none">
                                                            <div class="modal-content">
                                                                <p><?= $block->escapeHtml(__('Cancel Order Item %1', $productName)) ?></p>
                                                                <div id="order-refund-details">
                                                                    <span id="order-refund-amount"><?= $block->escapeHtmlAttr($refundNote) ?></span>
                                                                </div>
                                                                <div id="result-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"></div>
                                                                <div class="form-data">
                                                                    <?php if (!empty($reasonData)): ?>
                                                                        <label><?= $block->escapeHtml(__('Select Reason')) ?></label>
                                                                        <select id="ordercancel-reason-<?= $block->escapeHtmlAttr($orderItemIds) ?>"
                                                                                name="ordercancel-reason">
                                                                            <option value=""><?= $block->escapeHtml(__('Reason to cancel')) ?></option>
                                                                            <?php foreach ($reasonData as $reason): ?>
                                                                                <option value="<?= $block->escapeHtmlAttr($reason['reason_data']) ?>">
                                                                                    <?= $block->escapeHtml($reason['reason_data']) ?>
                                                                                </option>
                                                                            <?php endforeach; ?>
                                                                        </select>
                                                                    <?php endif; ?>
                                                                    <input id="ordercancel-submit-<?= $block->escapeHtmlAttr($orderItemIds) ?>" type="button"
                                                                           value="Send" name="submit">
                                                                </div>
                                                                <div id="loader-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" style="display:none;">
                                                                    <?= $block->escapeHtml(__('loading')) ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php else : ?>
                                                    <?php if ($isItemCancelled): ?>
                                                        <span class="order-item-cancelled"><?= $block->escapeHtml(__('Cancelled')) ?></span>
                                                    <?php elseif ($isItemReturned): ?>
                                                        <span class="order-item-returned"><?= $block->escapeHtml(__('Returned')) ?></span>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </td>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <div data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                                <p class="order-status">
                                    <a href="javascript:void(0);" class="order-status-popup"
                                       order-content-id="<?= $block->escapeHtmlAttr($_order->getId()) ?>">
                                        <?= $block->escapeHtml(__('Status')) ?>: <?= $block->escapeHtml($_order->getStatusLabel()) ?>
                                    </a>
                                </p>
                                <?php if ($_order->hasShipments()): ?>
                                    <p class="delivered-date">
                                        <?= $block->escapeHtml(__('Delivered on')) ?>
                                        <?= /* @noEscape */ $viewModel->getShipmentDataByOrderId($_order->getId()); ?>
                                    </p>
                                <?php endif; ?>
                                <?php if (!empty($orderStatus) && count($orderStatus) > 0): ?>
                                    <div class="order-status-modal"
                                         id="order-status-model-<?= $block->escapeHtmlAttr($_order->getId()) ?>" style="display: none;">
                                        <div class="modal-content">
                                            <div class="modal-progress-bar">
                                                <div class="card card-timeline">
                                                    <div style="display:none">
                                                        <span class="order-inc-no"><?= /* @noEscape */ $_order->getIncrementId()?></span>
                                                        <span class="order-customer-email"><?= /* @noEscape */ $_order->getCustomerEmail()?></span>
                                                        <span class="order-customer-id"><?= /* @noEscape */ $_order->getCustomerId()?></span>
                                                    </div>
                                                    <ul class="order-tracking-steps">
                                                        <?php $i = 1; ?>
                                                        <?php foreach ($orderStatus as $statusData): ?>
                                                            <li class="step <?= /* @noEscape */ (isset($statusData['status_date']) ? 'active' : ''); ?>">
                                                                <div><?= $block->escapeHtml($i) ?></div>
                                                                <span><?= $block->escapeHtml($statusData['status_title']) ?></span>
                                                                <?php if (isset($statusData['status_date'])): ?>
                                                                    <p><?= $block->escapeHtml($statusData['status_date']) ?></p>
                                                                <?php endif; ?>
                                                            </li>
                                                            <?php $i++; ?>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                </div>
                                                <div class="main-information track-order-help">
                                                    <?= /* @noEscape */ __('Have you any query?')?> <a class="need-help" id="order-status-help-<?= /* @noEscape */ $_order->getIncrementId()?>" href="javascript:void(0)"><?= /* @noEscape */ __('Need help.')?></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <?php $customerEmail = $_order->getCustomerEmail();
                                $orderItems = $_order->getAllItems();
                                $allSku = '';

                                foreach ($orderItems as $orderItem) {
                                    $allSku = $allSku . $orderItem->getSku() . ',';
                                }
                                ?>
                                <?php if ($_order->canCancel()): ?>
                                    <?php if ($isCancellable || $isReturnable): ?>
                                        <span class="order-request-pending">
                                    <?= $block->escapeHtml(__('Request Pending')) ?>
                                </span>
                                    <?php else : ?>
                                        <span id="<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"
                                              class="order-cancel return-order-button-from-list">
                                    <span class="action return cancel"><?= $block->escapeHtml(__('Return')) ?></span>
                                </span>
                                        <div id="order-return-popup<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"
                                             style="display:none">
                                            <div class="modal-content">
                                                <p><?= $block->escapeHtml(__('Return Order #%1', $_order->getRealOrderId())) ?></p>
                                                <div id="return-result-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"></div>
                                                <div class="form-data">
                                                    <?php if (!empty($returnReasonData)): ?>
                                                        <label><?= $block->escapeHtml(__('Select Reason')) ?></label>
                                                        <select name="order-return-reason"
                                                                id="order-return-reason-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>">
                                                            <option value=""><?= $block->escapeHtml(__('Reason to return')) ?></option>
                                                            <?php foreach ($returnReasonData as $reason): ?>
                                                                <option value="<?= $block->escapeHtmlAttr($reason['reason_data']) ?>">
                                                                    <?= $block->escapeHtml($reason['reason_data']) ?>
                                                                </option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    <?php endif; ?>
                                                    <div id="return-loader-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"
                                                         style="display:none;">
                                                        <?= $block->escapeHtml(__('loading')) ?>
                                                    </div>
                                                    <input type="button" value="Send" name="order-return-submit"
                                                           id="orderreturnsubmit-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>">
                                                </div>
                                            </div>
                                        </div>

                                        <span id="cancel-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" class="order-cancel cancel-order-button">
                                    <span class="action cancel"><?= $block->escapeHtml(__('Cancel')) ?></span>
                                </span>
                                        <div class="show-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?> modal" style="display: none;">
                                            <div class="modal-content">
                                                <span class="close-cancel-popup" id="closecancelpopup-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>">&times;</span>
                                                <p><?= $block->escapeHtml(__('Cancel Order #%1', $_order->getRealOrderId())) ?></p>
                                                <div id="result-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"></div>
                                                <div class="form-data">
                                                    <?php if (!empty($reasonData)): ?>
                                                        <label><?= $block->escapeHtml(__('Select Reason')) ?></label>
                                                        <select name="ordercancel-reason"
                                                                id="ordercancel-reason-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>">
                                                            <option value="">
                                                                <?= $block->escapeHtml(__('Reason to cancel')) ?></option>
                                                            <?php foreach ($reasonData as $reason): ?>
                                                                <option value="<?= $block->escapeHtmlAttr($reason['reason_data']) ?>">
                                                                    <?= $block->escapeHtml($reason['reason_data']) ?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    <?php endif; ?>
                                                    <div id="loader-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"
                                                         style="display:none;"><?= $block->escapeHtml(__('loading')) ?></div>
                                                    <input type="button" value="Send" name="submit" class="ordercancel-submit" id="ordercancelsubmit-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>"
                                                    >
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <?php if ($isCancellable): ?>
                                        <span class="order-cancelled"><?= $block->escapeHtml(__('Cancelled')) ?></span>
                                    <?php elseif ($isReturnable): ?>
                                        <span class="order-returned"><?= $block->escapeHtml(__('Returned')) ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                    <span class="order-view"><?= $block->escapeHtml(__('View Order')) ?></span>
                                </a>
                                <input type="hidden" name="recent-order-realid-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>">
                                <input type="hidden" name="recent-order-id-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= /* @noEscape */ $_order->getId() ?>">
                                <input type="hidden" name="recent-order-incid-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= /* @noEscape */ $_order->getIncrementId() ?>">
                                <input type="hidden" name="recent-order-website-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= /* @noEscape */ $storeUrl ?>">
                                <input type="hidden" name="order-cancel-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= (!$_order->canCancel()) ? 'true' : 'false'; ?>">
                                <input type="hidden" name="order-items-<?= $block->escapeHtmlAttr($_order->getId()) ?>" value="<?= /* @noEscape */ $allSku; ?>">
                                <input type="hidden" name="customer-email-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= /* @noEscape */ $customerEmail; ?>">
                                <input type="hidden" name="customer-phone-<?= $block->escapeHtmlAttr($_order->getRealOrderId()) ?>" value="<?= /* @noEscape */ $customerPhone; ?>">
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
                <input type="hidden" name="order-return-url" value="<?= /* @noEscape */ $block->getUrl('orderreturn/ajax/checkOrderReturn') ?>">
                <input type="hidden" name="order-return-sub-url" value="<?= /* @noEscape */ $block->getUrl('orderreturn/ajax/sendReturn') ?>">
                <input type="hidden" name="order-update-order" value="<?= /* @noEscape */ $block->getUrl('orderhistory/ajax/UpdateOrder') ?>">
                <input type="hidden" name="order-return-success" value="<?= /* @noEscape */ $block->getUrl('orderreturn/index/success') ?>">
                <input type="hidden" name="order-ajax-update-item" value="<?= /* @noEscape */ $block->getUrl('orderhistory/ajax/UpdateItem') ?>">
            </div>
        <?php else : ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
        <?php endif; ?>
    </div>
</div>

<?php
$subject = __('Request for Cancel of Order');
$customerSession = $viewModel->getCustomerSessionManager();
$fname = ''; $lname = ''; $email = '';
if ($customerSession->isLoggedIn()) {
    $fname = $customerSession->getCustomer()->getFirstname();
    $lname = $customerSession->getCustomer()->getLastname();
    $email = $customerSession->getCustomer()->getEmail();
}
?>

<div id="order-return-ticket-modal" style="display:none;">
    <div id="order-refund-details">
        <span id="order-refund-amount"></span>
    </div>
    <form class="form"
          action="<?= $block->escapeUrl($this->getUrl('mytickets/ajax/create')) ?>"
          id="ordercancel-popup-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <div id="ordercancelreturn_reason" class="alert alert-danger" role="alert"></div>
        <div class="row">
            <div class="col-sm-6">
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <select name="orddercancel_item" id="orddercancel_item" required="true" class="input-text">
                            <option value=""><?= $block->escapeHtml(__('Select Item')) ?></option>
                        </select>
                    </div>
                </div>
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_name" class="input-text" title="Name" name="orddercancel_name" required=""
                               type="text" value="<?= $block->escapeHtmlAttr($fname) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter Your Name')) ?>">
                    </div>
                </div>
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_last_name" class="input-text" title="Last Name" required=""
                               name="orddercancel_last_name" type="text"
                               value="<?= $block->escapeHtmlAttr($lname) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter Your Last Name')) ?>">
                    </div>
                </div>
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_email" class="input-text" required="" title="Email"
                               name="orddercancel_email"
                               type="email" <?= ($email != '') ? 'readonly="readonly"' : '' ?>
                               value="<?= $block->escapeHtmlAttr($email) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter email')) ?>">
                    </div>
                </div>
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_phone" class="input-text" title="Phone" required=""
                               name="orddercancel_phone" type="text" value=""
                               placeholder="<?= $block->escapeHtmlAttr((__('Enter Phone Number'))) ?>">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_brand" readonly="true" class="input-text" title="Brand"
                               required="" name="orddercancel_brand" type="text" value=""
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter Brand Name')) ?>">
                    </div>
                </div>
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_style" readonly="true" class="input-text" title="Style"
                               required="" name="orddercancel_style" type="text" value=""
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter Style')) ?>">
                    </div>
                </div>
                <div class="field name required cls_comm_input">
                    <div class="control">
                        <input id="orddercancel_keyword" readonly="true" class="input-text" title="Keyword"
                               required="" name="orddercancel_keyword" type="text"
                               value="<?= $block->escapeHtmlAttr(__('Order Cancel request')) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter Keyword')) ?>">
                    </div>
                </div>
                <div class="field remarks required cls_comm_input">
                    <div class="control">
                    <textarea id="orddercancel_remarks" class="input-text" title="Remarks" required=""
                              name="orddercancel_remarks" type="text" value=""
                              placeholder="<?= $block->escapeHtmlAttr(__('Enter Remarks')) ?>"></textarea>
                    </div>
                </div>
            </div>
            <div class="field name required spBtn">
                <div class="control">
                    <input type="hidden" name="orddercancel_tickettype" id="orddercancel_tickettype" value="0"/>
                    <input type="hidden" name="orddercancel_itemskus" id="orddercancel_itemskus" value=""/>
                    <input type="hidden" name="orddercancel_order_id" id="orddercancel_order_id" value=""/>
                    <input type="hidden" name="orddercancel_lang_code" id="orddercancel_lang_code"
                           value="<?= $block->escapeHtmlAttr($storeCode) ?>"/>
                    <input type="hidden" name="orddercancel_hdn_subject" id="orddercancel_hdn_subject" value=""/>
                    <input type="hidden" name="orddercancel_hdn_message" id="orddercancel_hdn_message" value=""/>
                    <input type="hidden" name="orddercancelreturn_requesttype" id="orddercancelreturn_requesttype"
                           value=""/>
                    <div class="mm-action">
                        <button id="orddercancel_btn_submit" class="btn btn-custom" name="orddercancel_btn_submit"
                                type="submit"><?= $block->escapeHtml(__('Submit')) ?></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="order-help-container" style="display:none">
    <div class="show-order-help modal-track-help">
        <div id="order-track-help" class="track-order-help">
            <form class="form"
                  action="<?= $block->escapeUrl($this->getUrl('mytickets/index/post')) ?>"
                  id="order-popup-form"
                  method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                  data-mage-init='{"validation":{}}'>
                <div class="main-information">
                    <div class="field order-number required cls_comm_input">
                        <div class="control">
                            <input id="keyword" class="input-text" title="Order Number"
                                   required="" name="keyword" type="text" value="" readonly
                                   placeholder="<?= $block->escapeHtmlAttr(__('Enter Order #')) ?>">
                        </div>
                    </div>
                    <div class="field email required cls_comm_input">
                        <div class="control">
                            <input id="order-email"  class="input-text" title="Style"
                                   required="" name="order-email" type="text" value="" readonly
                                   placeholder="<?= $block->escapeHtmlAttr(__('Email Address')) ?>">
                            <input id="order-status"  class="input-text" name="status" type="hidden" value="1"
                            >
                            <input id="customer_id" readonly  class="input-text" name="customer_id" type="hidden" value=""
                            >
                        </div>
                    </div>
                    <div class="field reason required cls_comm_input">
                        <div class="control">
                                            <textarea id="remarks" class="input-text" title="Reason" required=""
                                                      name="remarks" type="text"
                                                      placeholder="<?= $block->escapeHtmlAttr(__('Enter Reason')) ?>"></textarea>
                        </div>
                    </div>
                    <div class="field create-ticket">
                        <button id="create-ticket" class="btn btn-create-ticket" name="create-ticket"
                                type="submit"><?= $block->escapeHtml(__('Submit')) ?>
                        </button>
                    </div>
                </div>
            </form>
            <div class="ticket-created-success" style="display:none">
                <div class="response-container"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Dynamic_Orderreturn/js/recentorders" : {}
        }
    }
</script>

<div id="order-return-ticket-modal-item" style="display:none;">
    <div id="order-refund-details_item">
        <span id="order-refund-amount_item"></span>
    </div>
    <form class="form"
          action="<?= $block->escapeUrl($this->getUrl('mytickets/ajax/create')) ?>"
          id="ordercancel-popup-form-item"
          method="post"
          data-hasrequired="<?= /* @noEscape */ __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
        <div id="ordercancelreturn_reason_item"  class="alert alert-danger" role="alert"> </div>
        <div class="field name required cls_comm_input">
            <div class="control">
                <input id="orddercancel_name" class="input-text" title="Name" name="orddercancel_name" required="" type="text" value="<?= $block->escapeHtmlAttr($fname) ?>" placeholder="<?= /* @noEscape */ __('Enter Your Name') ?>">
            </div>
        </div>
        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_last_name" class="input-text" title="Last Name" required="" name="orddercancel_last_name" type="text" value="<?= $block->escapeHtmlAttr($lname) ?>" placeholder="<?= /* @noEscape */ __('Enter Your Last Name')?>"></div>
        </div>
        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_email" class="input-text" required="" title="Email" name="orddercancel_email" type="email" <?= ($email != '') ? 'readonly="readonly"' : '' ?> value="<?= $block->escapeHtmlAttr($email) ?>" placeholder="<?= /* @noEscape */ __('Enter email')?>"></div>
        </div>
        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_phone" class="input-text" title="Phone" required="" name="orddercancel_phone" type="text" value="" placeholder="<?= /* @noEscape */ __('Enter Phone Number')?>"></div>
        </div>
        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_brand_item" readonly="true" class="input-text" title="Brand" required="" name="orddercancel_brand" type="text" value="" placeholder="<?= /* @noEscape */ __('Enter Brand Name')?>"></div>
        </div>
        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_style_item" readonly="true" class="input-text" title="Style" required="" name="orddercancel_style" type="text" value="" placeholder="<?= /* @noEscape */ __('Enter Style')?>"></div>
        </div>
        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_keyword_item" readonly="true" class="input-text" title="Keyword" required="" name="orddercancel_keyword" type="text" value="<?= /* @noEscape */ __('Order Cancel request')?>" placeholder="<?= /* @noEscape */ __('Enter Keyword')?>"></div>
        </div>

        <div class="field name required cls_comm_input">
            <div class="control"><input id="orddercancel_image" class="input-text" title="Image" required="" name="orddercancel_image" type="text" value="" placeholder="<?= /* @noEscape */ __('URL of Image')?>"></div>
        </div>
        <div class="field remarks required cls_comm_input">
            <div class="control"><textarea id="orddercancel_remarks" class="input-text" title="Remarks" required="" name="orddercancel_remarks" type="text" value="" placeholder="<?= /* @noEscape */ __('Enter Remarks')?>"></textarea></div>
        </div>
        <div class="field name required spBtn">
            <div class="control">
                <input type="hidden" name="orddercancel_tickettype" id="orddercancel_tickettype" value="0" />
                <input type="hidden" name="orddercancel_itemskus" id="orddercancel_itemskus" value="" />
                <input type="hidden" name="orddercancel_order_id" id="orddercancel_order_id" value="" />
                <input type="hidden" name="orddercancel_lang_code" id="orddercancel_lang_code" value="<?= $block->escapeHtmlAttr($storeCode) ?>" />
                <input type="hidden" name="orddercancel_hdn_subject" id="orddercancel_hdn_subject" value="" />
                <input type="hidden" name="orddercancel_hdn_message" id="orddercancel_hdn_message" value="" />
                <input type="hidden" name="orddercancelreturn_requesttype" id="orddercancelreturn_requesttype" value="" />
                <div class="mm-action">
                    <button id="orddercancel_btn_submit_item"
                            class="btn btn-custom"
                            name="orddercancel_btn_submit_item" type="submit">
                        <?= /* @noEscape */ __('Submit') ?>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
<!--END Request Ticket Creation form for Not eligible Item return and Order cancel-->

<div id="order-return-ticket-modal-exist" style="display:none;">
    <span class="already-exist">
        <strong><?= /* @noEscape */ __('A request for this has already been made , Please check under My returns') ?></strong>
    </span>
</div>
<div id="dynamic-orders-list-info" data-store="<?= $block->escapeJs($storeCode) ?>" data-lang="<?= $block->escapeJs($storeUrl) ?>"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Dynamic_Orderreturn/js/orders-list": {
            }
        }
    }
</script>
