<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container"
      style="width:<?= $block->escapeHtmlAttr($block->getWidth()) ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= ($block->getRatio() * 100) ?>%;">
        <img alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>"
             class="<?= $block->escapeHtmlAttr($block->getClass()) ?>"
             loading="lazy"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtml($value) ?>"
            <?php endforeach; ?>
            src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
            width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
            height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"/>
    </span>
</span>
