<?php /** \Magento\Framework\View\Element\Template @var $block */?>
<meta name="smartbanner:icon-apple"
      content="<?= $this->getViewFileUrl('') ?>"/>
<meta name="smartbanner:icon-google"
      content="<?= $this->getViewFileUrl('') ?>"/>
<meta name="smartbanner:button-url-apple" content="<?= $block->getUrl(''); ?>"/>
<meta name="smartbanner:button-url-google" content="<?= $block->getUrl(''); ?>"/>
