<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $popup = $_helper->getConfig('porto_settings/newsletter');
    $enabled =0 ;
    if(isset($popup['enable'])){
        $enabled = $popup['enable'];
        if($enabled == 1 || $enabled ==2){
        $delay = 0;
        if(isset($popup["delay"])) {
            if(is_numeric($popup["delay"]))
                $delay = $popup["delay"];
        }
?>
<style type="text/css">
<?php
    if($popup["custom_style"]){
        echo $popup["custom_style"];
    }
?>
#newsletter_popup{
<?php
    if($popup["width"]){
        echo "width:".$popup["width"].";";
    }
    if($popup["height"]){
        echo "height:".$popup["height"].";";
    }
    if($popup["bg_color"]){
        echo "background-color:".$popup["bg_color"].";";
    }
    if(isset($popup["bg_image"]) && $popup["bg_image"]){
        $folderName = \Smartwave\Porto\Model\Config\Backend\Image\Newsletterbg::UPLOAD_DIR;
        $path = $folderName . '/' . $popup["bg_image"];
        $imageUrl = $_helper->getBaseUrl() . $path;
?>
    background-image:url(<?php echo $imageUrl;?>);
<?php
    }
?>
}
</style>
<div class="newsletter" id="newsletter_popup" style="display: none ">
    <div class="block-content">
        <?php
            if(isset($popup["logo_src"]) && $popup["logo_src"]){
                $folderName = \Smartwave\Porto\Model\Config\Backend\Image\Newsletterlogo::UPLOAD_DIR;
                $path = $folderName . '/' . $popup["logo_src"];
                $logoUrl = $_helper->getBaseUrl() . $path;
        ?>
                <img src="<?php echo $logoUrl; ?>" alt="" />
        <?php
            }
        ?>
        <?php echo $popup["content"]; ?>
        <form class="form subscribe"
            novalidate
            action="<?php echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <input name="email" type="email" id="footer_newsletter"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php echo __('Go') ?>" type="submit">
                    <span><?php echo __('Go') ?></span>
                </button>
            </div>
        </form>
        <div class="subscribe-bottom">
            <input type="checkbox" id="newsletter_popup_dont_show_again"/>
            <label for="newsletter_popup_dont_show_again"><?php echo __("Don't show this popup again"); ?></label>
        </div>
    </div>
</div>

<div id="subscribe-popup-enabled-info" data-delay="<?php echo $delay; ?>" data-info="<?php echo $enabled; ?>"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Newsletter/js/subscribe-popup": {
            }
        }
    }
</script>
<?php
        }
    }
?>
