<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_helper = $this->helper('WeltPixel\ProductPage\Helper\Data'); ?>
<?php $selectMaxValue = $_helper->getQtySelectMaxValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $addToCartClass = !$block->shouldRenderQuantity() ? 'full-width-btn' : ''; ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php //if ($block->shouldRenderQuantity()): ?>
                <div class="field qty abc">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                    <div class="control">
                        <select name="qty"
                                title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                                id="qty"
                                class="input-text qty">
                            <?php foreach (range(1, $selectMaxValue) as $number) : ?>
                                <option value="<?php echo $number ?>"><?php echo $number ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php //endif; ?>
            <div class="actions  <?php echo $addToCartClass; ?>">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>

<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "WeltPixelProductPageAddtoCart": {}
            }
        }
    </script>
<?php endif; ?> 