<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist">
       <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
       <span class="icon icon-icon-whishlist"></span>
    </a>
       <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wishlist": {
                            "component": "BelVG_GuestWishlist/js/view/wishlist"
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>


