<?php
$ddHelper = $this->helper("\Dynamic\HomepageApi\Helper\Data");
$category = $ddHelper->getRegistryManager()->registry('current_category'); //Get Current Category
?>
<?php if($category): ?>
    <?php $subcats = $category->getChildrenCategories(); ?>
    <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
    <?php if(count($subcats) > 0 ) : ?>
        <div class="block-category-list">
            <div class="block-title">
                <strong><?= $block->escapeHtml($category->getName()) ?></strong>
            </div>
            <div class="block-content">
                <ol class="items">
                    <?php foreach($subcats as $subcat) : ?>
                        <li class="item">
                            <a href="<?= $block->escapeUrl($subcat->getUrl()) ?>">
                                <?= $block->escapeHtml($subcat->getName()) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <?php $elementJs = 'category_filter_nav' ?>
            <script type="text/x-magento-init">
            {
                "*": {
                    "MageplazaLayeredNav": {
                        "elementJs": "<?= $elementJs ?>"
                    }
                }
            }
            </script>
        </div>
    <?php endif; ?>
<?php endif; ?>