<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Edit $block */

$id = $block->getRequest()->getParam('id');

$addressBook = $block->getUrl('customer/address/index');
if ($id) {
    $actionUrl = $block->getUrl('luxuryunlimited_customer/address/formpostajax', ['id' => $id]);
} else {
    $actionUrl = $block->getUrl('luxuryunlimited_customer/address/formpostajax');
}
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<form class="form-address-edit accountInfo form-address-add-section"
      action="<?= $block->escapeUrl($actionUrl) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset contact-info">
        <legend class="legend"><span><?= /* @noEscape */ __('Contact Information')?></span></legend>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>
        <div class="fields field-common-section">
            <?php if ($_telephone->isEnabled()) : ?>
                <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php if ($_company->isEnabled()) : ?>
                <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php if ($_fax->isEnabled()) : ?>
                <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
            <?php endif ?>
        </div>
    </fieldset>
    <fieldset class="fieldset address-info">
        <legend class="legend"><span><?= /* @noEscape */ __('Address')?></span></legend>
        <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
        <div class="fields street required">
            <div class="field">
                <label class="label" for="street_1">
                    <span><?= $block->escapeHtml(__('Street Address')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                       id="street_1"
                       placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                </div>
            </div>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++) : ?>
                <div class="field additional">
                    <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                        <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="street[]"
                                value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                                class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    </div>
                </div>
            <?php endfor; ?>
        </div>

        <?php if ($this->helper(\Magento\Customer\Helper\Address::class)->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('vat_id')) ?>"
                           placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="fields field-common-section">
            <div class="field zip required">
                <label class="label" for="zip">
                    <span><?= $block->escapeHtml(__('Postal Code')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                        name="postcode"
                        value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                        id="zip"
                        placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                        class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                    <div role="alert" class="message warning" style="display:none">
                        <span></span>
                    </div>
                </div>
            </div>
            <div class="field city required">
                <label class="label" for="city">
                    <span><?= $block->escapeHtml(__('Enter Your City')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                        name="city"
                        value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                        class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>"
                        placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                        id="city">
                </div>
            </div>
        </div>
         <div class="fields field-common-section">
            <div class="field country required">
                <label class="label" for="country">
                    <span><?= $block->escapeHtml(__('Select Your Country')) ?></span>
                </label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <div class="field region required">
                <label class="label" for="region_id">
                    <span><?= $block->escapeHtml(__('Select Your State')) ?></span>
                </label>
                <div class="control">
                    <select id="region_id" name="region_id"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                            class="validate-select region_id" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <input type="text"
                        id="region"
                        name="region"
                        value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                        placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                        class="input-text validate-not-number-first <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
                </div>
            </div>
        </div>

        <div class="fields choice-address">
            <?php if ($block->isDefaultBilling()) : ?>
                <div class="message info">
                    <span><?= $block->escapeHtml(__("It's a default billing address.")) ?></span>
                </div>
            <?php elseif ($block->canSetAsDefaultBilling()) : ?>
                <div class="form-block checkbox field choice set billing">
                    <input type="checkbox" id="primary_billing" name="default_billing" class="checkbox">
                    <span class="checkmark"></span>
                    <label for="primary_billing"><i class="checkbox"></i><span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span></label>
                </div>
            <?php else : ?>
                <input type="hidden" name="default_billing" value="1" />
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()) : ?>
                <div class="message info">
                    <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
                </div>
            <?php elseif ($block->canSetAsDefaultShipping()) : ?>
                <div class="form-block checkbox field choice set shipping">
                    <input type="checkbox" id="default_shipping" name="default_shipping" class="checkbox">
                    <span class="checkmark"></span>
                    <label for="default_shipping"><i class="checkbox"></i><span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span></label>
                </div>
            <?php else : ?>
                <input type="hidden" name="default_shipping" value="1">
            <?php endif; ?>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button"
                    class="action save primary save-address-button"
                    data-action="save-address"
                    title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>

<div data-id="<?= $block->escapeHtml($id); ?>" id="address-inf-block"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/address-edit": {
            }
        }
    }
</script>

