<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="forgotpassword-container">
    <form class="form password forget"
          action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <legend class="fieldset-legend">
                <span><?= $block->escapeHtml(__('Forgot Password')) ?></span>
            </legend>
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
            <div class="field email required">
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' placeholder="<?= $block->escapeHtml(__('Email Address*')) ?>" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
            </div>
            <div class="secondary forgot-login">
                <a class="action primary back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Back to Login')) ?></span></a>
            </div>
        </div>
    </form>
</div>
