<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist $block */
?>

<?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="form-wishlist-items" id="wishlist-view-form"
      data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()])) ?>" method="post">
        <?= $block->getChildHtml('top') ?>
        <?php if ($block->hasWishlistItems()) : ?>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
            <div>
                <input id="sharing-link" type="hidden" value="<?= $block->getSharingLink() ?>"/>

            </div>
        <?php else : ?>
        <div class="cart-empty">
            <div class="no-page" style="text-align: center">
                <img alt="<?= /* @noEscape */ __('Oops') ?>" src="<?= $block->getViewFileUrl('images/oops.svg') ?>">
                <h3><?= __("You Don't Seem to Have Any Favourites Yet "); ?> </h3>
                <p class="re-result-desc" style="text-align: center">
                        <em class="icon-user porto-icon-user"></em> <?= __('Use the heart icon to save products '); ?>
                </p>
                <p class="re-result-desc" style="text-align: center">
                    <i class="icon-wishlist far fa-heart"></i> <?= __(' Join or login to view saved items on different devices  '); ?>
                </p>
                <div class="re-result-btns" style="text-align: center">
                    <a class="action primary" href="<?php echo $block->getUrl('brands'); ?>"><?= $block->escapeHtml(__('Continue Shopping')); ?></a>
                </div>
            </div>
        </div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
        <div class="btnAction">
            <?= $block->getChildHtml('control_buttons') ?>
        </div>
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
      <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
          <% if (data.qty) { %>
          <input name="qty" value="<%- data.qty %>">
          <% } %>

          <% if (data.item) { %>
          <input name="item" value="<%- data.item %>">
          <% } %>

          <% if (data.entity) { %>
          <input name="entity" value="<%- data.entity %>">
          <% } %>
      </form>
    </script>
    <div class="toolbar wishlist-toolbar"><br><?= $block->getChildHtml('wishlist_item_pager'); ?></div>
<?php endif ?>
<script type="text/javascript">
    function copySharingLin() {
        var currentUrl = document.getElementById('sharing-link');
        currentUrl.type = 'text';
        currentUrl.select();
        document.execCommand("copy");
        currentUrl.type = 'hidden';
    }
</script>
