<?php
$websites = $block->getAllWebsites();
$cookiebaseUrl = $block->getBaseUrlFromCookies();
$currentBaseUrl = $block->getCurrentUrl();
$currentStores = $block->getCurrentStores();
$currentWebsite = $block->getCurrentWebsite();
$currentStore = $block->getCurrentStore();
?>

<div id="cookie-popup-window" style="display:none;">
    <select name="websites" id="websites">
          <?php foreach ($websites as $website): ?>
          <option value="<?= /* @noEscape */ $website->getCode(); ?>" 
                <?= ($website->getCode() == $currentWebsite) ?
                "selected" : "" ; ?>><?= /* @noEscape */ $website->getName(); ?>
            </option>
          <?php endforeach; ?>
    </select>
    <select name="store" id="store">
        <?php foreach ($currentStores as $store): ?>
        <option value="<?= /* @noEscape */ $store->getStoreId() ?>" 
            <?= ($store->getId() == $currentStore) ? "selected" : ""; ?>>
            <?= /* @noEscape */ $store->getName() ?>
        </option>
        <?php endforeach; ?>
    </select>
    <button name="cancel" id="cancel">Cancel</button>
    <button name="redirect" id="redirect">Ok</button>
</div>

<script>
require([ 'jquery','Magento_Ui/js/modal/modal','mage/cookies'], function($,modal) {

       var options = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        title: '',
        modalClass: 'custom-window-block',
        buttons: [],
        closed: function () {
            $.cookie('dont-show', 'true');
        }
    };


    
    <?php if ($cookiebaseUrl == ''): ?>
        if ($.cookie('dont-show') != 'true') {
              var popup = modal(options, $('#cookie-popup-window'));
            $("#cookie-popup-window").modal("openModal");
        }
    <?php else: ?>
        <?php if ($currentBaseUrl !== $cookiebaseUrl): ?>
        //    window.location.href = "<?= /* @noEscape */ $cookiebaseUrl ?>";
        <?php endif; ?>
    <?php endif; ?>

    $(document).on('change',"[name='websites']",function(){
        var customurl = "<?= /* @noEscape */ $block->getUrl().'storeredirect/getstores/index'?>";
        $.ajax({
            url: customurl,
            type: 'POST',
            dataType: 'json',
            data: {
                websiteCode: $(this).val(),
            },
            complete: function(response) {           
                var $select = $('#store'); 
                $select.find('option').remove(); 
                var storeData = response.responseJSON; 
                $.each(storeData,function(key, value) 
                {
                    console.log(value);
                    $select.append('<option value=' + value.code + '>' + value.name + '</option>');
                });
            }
        });
    });

    $(document).on('click',"[name='cancel']",function(){
        $("#cookie-popup-window").modal("closeModal");
    }); 

    $(document).on('click',"[name='site-switcher']",function(){
        var popup = modal(options, $('#cookie-popup-window'));
        $("#cookie-popup-window").modal("openModal");
    }); 

    $(document).on('click',"[name='switcher-dropdown']",function(){
        var popup = modal(options, $('#cookie-popup-window'));
        $("#cookie-popup-window").modal("openModal");
    }); 

   

    $(document).on('click',"[name='redirect']",function(){
        var url = "<?= /* @noEscape */ $block->getUrl().'storeredirect/getbaseurl/index'?>";
        $.ajax({
            url: url,
            type: 'POST',
            dataType: 'json',
            data: {
                storeCode: $('#store').val(),
            },
            complete: function(response) {
                $.cookie('dont-show', 'true');
                window.location.href = response.responseJSON.base_url;
            }
        });
    }); 
});

</script>