<?php
    $porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $product_view = $porto_helper->getConfig('porto_settings/product');
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
    $sticky_header = "no-sticky-header";
    if($porto_helper->getConfig('porto_settings/header/sticky_header')) {
        $sticky_header = "";
    }
    $_product = $block->getProduct();
    if (isset($product_view['enable_addtocart_sticky']) && $product_view['enable_addtocart_sticky']):
        $productImage = $_imagehelper->init($_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(50);
        $productImageUrl = $productImage->getUrl();
?>
<div class="sticky-product hide <?= $block->escapeHtmlAttr($sticky_header) ?>">
    <div class="container">
        <div class="sticky-image">
           <img class="product-image-photo default_image" src="<?= $block->escapeUrl($productImageUrl) ?>" alt="<?= $block->escapeHtmlAttr($productImage->getLabel()) ?>"/>
        </div>
        <div class="sticky-detail">
            <div class="product-name-area">
                <h2 class="product-name"><?= $block->escapeHtml($_helper->productAttribute($_product, $_product->getName(), 'name')) ?></h2>
                <div class="product-info-price"></div>
            </div>
        </div>
        <?php $buttonTitle = __('Add to Cart'); ?>
        <?php if ($_product->isSaleable()): ?>
        <div class="actions">
            <button type="button"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart" id="product-addtocart-button-clone">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Catalog/js/product-custom": {
            }
        }
    }
</script>
<?php
    endif;
?>
<?php if (isset($product_view['move_tab']) && $product_view['move_tab']): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/product-info-detailed": {
                }
            }
        }
    </script>
<?php endif; ?>
