
<ul>
    <li>
        <div class="iconBlock">
            <i class="icon-icon-shopping"></i>
        </div>
        <div class="contentBlock">
            <span class="spanTitle"><?= /* @noEscape */ __('FREE SHIPPING') ?></span>
            <span class="spanContent"><?= /* @noEscape */ __('Free shipping on all over $99.') ?></span>
        </div>
    </li>
    <li>
        <div class="iconBlock">
            <i class="icon-icon-sales"></i>
        </div>
        <div class="contentBlock">
            <span class="spanTitle"><?= /* @noEscape */ __('MONEY BACK GUARANTEE') ?></span>
            <span class="spanContent"><?= /* @noEscape */ __('100% money back guarantee.') ?></span>
        </div>
    </li>
    <li>
        <div class="iconBlock">
            <i class="icon-icon-phone"></i>
        </div>
        <div class="contentBlock">
            <span class="spanTitle"><?= /* @noEscape */ __('ONLINE SUPPORT 24/7') ?></span>
            <span class="spanContent"><?= /* @noEscape */ __('Lorem ipsum dolor sit sit amet.') ?></span>
        </div>
    </li>
    <li>
        <div class="iconBlock">
            <i class="icon-icon-return"></i>
        </div>
        <div class="contentBlock">
            <span class="spanTitle"><?= /* @noEscape */ __('GUARANTEED DELIVERY') ?></span>
            <span class="spanContent"><?= /* @noEscape */ __('15th October 2020') ?></span>
        </div>
    </li>
</ul>
