<?php
	$porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
	$page_layout = $porto_helper->getConfig('porto_settings/product/page_layout');
?>
<?php if (!isset($page_layout) || $page_layout == "2columns-right"): ?>
	<div class="side-overlay overlay"></div>
	<a href="javascript:void(0);" class="right-side-open"><em class="porto-icon-reply"></em></a>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/product/view/side-popup": {}
            }
        }
    </script>
<?php endif; ?>

