<?php $_product = $block->getProduct(); ?>
<div class="social-media-icons">
    <!-- Email -->
    <a href="mailto:?subject=<?= $block->escapeHtmlAttr($_product->getName()) ?>">
        <i class="far fa-envelope" aria-hidden="true"></i>
    </a>
    <!-- WhatsApp -->
    <a target="_blank" href="https://api.whatsapp.com/send?text=<?= $block->escapeHtmlAttr(urlencode($_product->getProductUrl())) ?>">
            <i class="fab fa-whatsapp"></i></a>
    <!-- Facebook -->
    <a href="https://www.facebook.com/sharer/sharer.php?u=<?= $block->escapeHtmlAttr(urlencode($_product->getProductUrl())) ?>&t=<?= $block->escapeHtmlAttr(urlencode($_product->getName())) ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="<?= /* @noEscape */ __('Share on facebook') ?>">
        <i class="fab fa-facebook-f" aria-hidden="true"></i>
    </a>
    <!-- TWITTER -->
    <a href="http://twitter.com/home/?status=<?= $block->escapeHtmlAttr(urlencode($_product->getProductUrl())) ?>(<?= $block->escapeHtmlAttr(urlencode($_product->getName())) ?>)" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="<?= /* @noEscape */ __('Share on Twitter') ?>">
        <i class="fab fa-twitter" aria-hidden="true"></i>
    </a>
    <!-- Pinterest -->
    <?php /* <a href="https://pinterest.com/pin/create/button/?url=<?php //echo urlencode($_product->getProductUrl()); ?>&media=<?php //echo urlencode($_product->getImageUrl());?> &description=<?php //echo urlencode($_product->getName()); ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Pin it">
        <i class="fab fa-pinterest-p"></i>
    </a> */ ?>
    <!-- Google Plus -->
    <a href="https://plus.google.com/share?url=<?= $block->escapeHtmlAttr(urlencode($_product->getProductUrl())) ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="<?= /* @noEscape */ __('Share on Google Plus') ?>">
        <i class="fab fa-google-plus-g"></i>
    </a>
</div>
