<?php
/**
 * @var WeltPixel\FullPageScroll\Block\FullPageScroll $_blocks
 */
$_blocks      = $block->cmsBlockFiltered();
$_countBlocks = count($_blocks);
?>
<?php if ($block->enable() && $_countBlocks > 0): ?>
    <div id="fullpage">
        <?php foreach ($_blocks as $_block) : ?> 
            <?=  /* @escapeNotVerified */ $block->escapeHtml($_block) ?>
        <?php endforeach; ?>
        <div
            class="section fp-auto-height"
            for="footer"
            id="section<?= /* @noEscape */ $_countBlocks; ?>">
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "WeltPixelFullPageScroll": {
                "countBlocks" : <?= /* @noEscape */ $_countBlocks ?>
            }
        }
    }
    </script>
<?php endif; ?>