<?php

/**
 * @var \Dynamic\Mytickets\Block\TicketCounter $block
 * @var \Magento\Framework\Escaper $escaper
 */
$msg_code = '';
$query = [];
if ($block->isLoggedIn()):
    $message_count = $block->getCustomerAllTicketUnreadMessageCount();
    if ($message_count > 0):
        $msg_code = $block->getLastRepliedTicketCode();
        $query = ['_query' => ['tcode'  =>  $msg_code]];

    ?>
    <div class="utilities notification-area link unread-count-link">
        <a href="<?= $block->escapeUrl($block->getUrl('orderreturn/customer/tickets/', $query)) ?>" class="action notification my-notification unread-link">
            <i class="icon-notifications"></i>
            <span class="unread-msg-cnt"><?= $escaper->escapeHtml($message_count) ?></span>
        </a>
        <span class="msg"><?= $escaper->escapeHtml($message_count) . ' ' .  $block->escapeHtml(__('Unread tickets')) ?></span>
    </div>
    <?php endif; ?>
<?php endif; ?>
