<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
$loginUrl = $block->getBaseUrl().'customer/account/loginPost/';
?>
<h1 class="hed"><?= /* @noEscape */ __('Track Your Order');?></h1>


<div class="login-container">
    <div class="block block-customer-login">
      <div class="block-title">
          <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
      </div>
      <div class="block-content" aria-labelledby="block-customer-login-heading">
          <form class="form form-login"
                action="<?= $block->escapeUrl($loginUrl) ?>"
                method="post"
                id="login-form"
                data-mage-init='{"validation":{}}'>
              <?= $block->getBlockHtml('formkey') ?>
              <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                  <legend><?= $block->escapeHtml(__('Registered Customers')) ?></legend>
                  <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                  <div class="field email required">
                      <div class="control">
                          <input placeholder="<?= $block->escapeHtml(__('Email')) ?>" name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" id="email" autocomplete="off" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                          <div class="clslogin cls_user"></div>
                      </div>
                  </div>
                  <div class="field password required">
                      <div class="control cls_password">
                          <input placeholder="<?= $block->escapeHtml(__('Password')) ?>" name="login[password]" type="password" autocomplete="off" class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                          <div class="clslogin cls_eye"></div>
                      </div>
                  </div>
                  <?= $block->getChildHtml('form_additional_info') ?>
                  <div class="actions-toolbar">
                      <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
            <div class="secondary cls_forget"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>

          </div>
              </fieldset>
          </form>
      </div>
    </div>
<!-- block-customer-login end-->
<!-- check-order-container start-->
    <div class="check-order-container block block-new-customer ">
        <div class="contentBlock">
          <div class="block-title">
              <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= /* @noEscape */ __('Guest Users') ?></strong>
          </div>
          <div class="notte"><?= /* @noEscape */ __('Please enter order number to track your order.') ?></div>
        </div>
        <div class="formBlock">
        <form class="form form-orders-search"
          id="oar-widget-orders-and-returns-form"
          data-mage-init='{"ordersReturns":{}, "validation":{}}'
          action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
          method="post" name="guest_post">
        <fieldset class="fieldset">
            <legend><?= $block->escapeHtml(__('Orders')) ?></legend>
            <div class="field id required">
                <label class="label" for="oar-order-id"><span><?= $block->escapeHtml(__('Order ID')) ?></span></label>

                <div class="control form-control">
                    <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field lastname required">
                <label class="label" for="oar-billing-lastname"><span><?= $block->escapeHtml(__('Billing Last Name')) ?></span></label>

                <div class="control form-control">
                    <input type="text" class="input-text" id="oar-billing-lastname" name="oar_billing_lastname"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field find required">
                <label class="label" for="quick-search-type-id"><span><?= $block->escapeHtml(__('Find Order By')) ?></span></label>

                <div class="control form-control">
                    <select name="oar_type" id="quick-search-type-id" class="select">
                        <option value="email"><?= $block->escapeHtml(__('Email')) ?></option>
                        <option value="zip"><?= $block->escapeHtml(__('ZIP Code')) ?></option>
                    </select>
                </div>
            </div>
            <div id="oar-email" class="field email required">
                <label class="label" for="oar_email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>

                <div class="control form-control">
                    <input type="email" class="input-text" id="oar_email" name="oar_email"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div id="oar-zip" class="field zip required">
                <label class="label" for="oar_zip"><span><?= $block->escapeHtml(__('Billing ZIP Code')) ?></span></label>

                <div class="control form-control">
                    <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Continue')) ?>" class="action submit primary login">
                    <span><?= $block->escapeHtml(__('Continue')) ?></span>
                </button>
            </div>
        </div>
        </form>
        </div>
    </div>
<!-- check-order-container end-->
</div>
<!-- login-container end-->
