<?php
/**
 * @var WeltPixel\FullPageScroll\Block\FullPageScroll $_blocks
 */
$_blocks      = $block->cmsBlockFiltered();
$_countBlocks = count($_blocks);
?>
<?php if ($block->enable() && $_countBlocks > 0): ?>
    <div id="fullpage">
        <?php
        foreach ($_blocks as $_block) {
            echo /* @escapeNotVerified */ $block->escapeHtml($_block);
        }
        ?>
        <div
            class="section fp-auto-height"
            for="footer"
            id="section<?= /* @noEscape */ $_countBlocks; ?>">
        </div>
    </div>
    <script>
        require(['jquery', 'fullpagescroll'],
            function ($, FullPageScroll) {
                FullPageScroll.action(<?= /* @noEscape */ $_countBlocks; ?>);
                jQuery(window).trigger('resize');
            });
    </script>
<?php endif; ?>
