<?php
/**
 * Top menu for store
 *
 * @var \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $block->helper(\Smartwave\Megamenu\Helper\Data::class);
    $_config = $_helper->getConfig('sw_megamenu');
    $columnsLimit = 0;
if ($_config['general']['enable']) {
    ?>
    <?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul>
    <?= $block->escapeHtml($_menu); ?>
    </ul>
</nav>

<script>
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
    });
</script>
    <?php
} else {
    ?>
    <?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
    <?= /* @escapeNotVerified */ $block->escapeHtml($_menu); ?>
    </ul>
</nav>

    <?php
}
?>
