<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Company $block */
    $layout   = $this->getRequest()->getFullActionName();
?>
<div class="field company <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="company" class="label">
        <span>
            <?= $block->escapeHtml(__('Company')) ?>
        </span>
    </label>
    <div class="control">
            <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper(\Magento\Customer\Helper\Address::class)
                     ->getAttributeValidationClass('company')
            );
            ?>
        <input type="text"
               name="company"
               id="company"
               value="<?= $block->escapeHtmlAttr($block->getCompany()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Company')) ?>"
            <?php if ($layout == 'customer_address_form') : ?>
                placeholder="<?= $block->escapeHtml(__('Company')) ?>"
            <?php endif; ?>
               class="input-text <?= $_validationClass ?: '' ?>"
         >
    </div>
</div>
