<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Fax $block */
    $layout   = $this->getRequest()->getFullActionName();
?>

<div class="field fax <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="fax" class="label">
        <span>
            <?= $block->escapeHtml(__('Fax')) ?>
        </span>
    </label>
    <div class="control">
            <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper(\Magento\Customer\Helper\Address::class)
                     ->getAttributeValidationClass('fax')
            );
            ?>
        <input type="text"
               name="fax"
               id="fax"
               value="<?= $block->escapeHtmlAttr($block->getFax()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Fax')) ?>"
            <?php if ($layout == 'customer_address_form') : ?>
                placeholder="<?= $block->escapeHtml(__('Fax')) ?>"
            <?php endif; ?>
               class="input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
