<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Name $block */

$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
$layout   = $this->getRequest()->getFullActionName();
?>
<?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()) : ?>
        <div class="fields <?= $block->escapeHtmlAttr($block->getContainerClassName()) ?>">
<?php else : ?>
    <div class="fields field-common-section">
<?php endif; ?>
    <div class="field field-name-firstname required <?php if ($prefix) { ?>prifix-field<?php } ?>">
        <label for="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>" class="label">
            <span><?= $escaper->escapeHtml(__('First Name')) ?></span>
        </label>
        <?php if ($prefix) : ?>
            <div class="control prifix-input-with-option">
        <?php endif; ?>
            <?php if ($prefix) : ?>
                <?php if ($block->getPrefixOptions() === false) : ?>
                    <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                           name="<?= $block->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getObject()->getPrefix()) ?>"
                           title="<?= $block->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                           class="input-prefix input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>" <?= $block->isPrefixRequired() ? ' data-validate="{required:true}"' : '' ?>>
                <?php else : ?>
                    <select id="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                            name="<?= $block->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                            title="<?= $block->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                            class="input-prefix <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?> prefix-select" <?= $block->isPrefixRequired() ? ' data-validate="{required:true}"' : '' ?> >
                        <?php foreach ($block->getPrefixOptions() as $_option) : ?>
                            <option value="<?= $block->escapeHtmlAttr($_option) ?>"<?php if ($block->getObject()->getPrefix() == $_option) : ?> selected="selected"<?php endif; ?>>
                                <?= $block->escapeHtml(__($_option)) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            <?php endif; ?>

            <?php /* if ($prefix) : ?>
                    <div class="control main">
            <?php endif; */ ?>
                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
                   name="<?= $block->escapeHtmlAttr($block->getFieldName('firstname')) ?>"
                   value="<?= $block->escapeHtmlAttr($block->getObject()->getFirstname()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getStoreLabel('firstname')) ?>"
                   placeholder="<?= $block->escapeHtml($block->getStoreLabel('firstname')) ?>"
                   class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('firstname')) ?> <?php if ($prefix) : ?>prefix-text<?php endif; ?>" <?= ($block->getAttributeValidationClass('firstname') == 'required-entry') ? ' data-validate="{required:true}"' : '' ?>>
            <?php /* if ($prefix) : ?>
                <div class="control main">
            <?php endif; */ ?>
        <?php if ($prefix) : ?>
            </div>
        <?php endif; ?>
    </div>

    <?php if ($middle) : ?>
        <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
        <div class="field field-name-middlename<?= $isMiddlenameRequired ? ' required' : '' ?>">
            <label for="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('middlename')) ?></span></label>
            <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"
                   name="<?= $block->escapeHtmlAttr($block->getFieldName('middlename')) ?>"
                   value="<?= $block->escapeHtmlAttr($block->getObject()->getMiddlename()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getStoreLabel('middlename')) ?>"
                   placeholder="<?= $block->escapeHtml($block->getStoreLabel('middlename')) ?>"
                <?php if ($layout == 'customer_address_form') : ?>
                    placeholder="<?= $block->escapeHtml($block->getStoreLabel('middlename')) ?>"
                <?php endif; ?>
                   class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('middlename')) ?>" <?= $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
        </div>
    <?php endif; ?>

    <div class="field field-name-lastname required">
        <label for="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>" class="label">
            <span><?= $block->escapeHtml($block->getStoreLabel('lastname')) ?></span>
        </label>
        <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
                name="<?= $block->escapeHtmlAttr($block->getFieldName('lastname')) ?>"
                value="<?= $block->escapeHtmlAttr($block->getObject()->getLastname()) ?>"
                title="<?= $block->escapeHtmlAttr($block->getStoreLabel('lastname')) ?>"
                placeholder="<?= $block->escapeHtml($block->getStoreLabel('lastname')) ?>"
            <?php if ($layout == 'customer_address_form') : ?>
                placeholder="<?= $block->escapeHtml($block->getStoreLabel('lastname')) ?>"
            <?php endif; ?>
                class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('lastname')) ?>" <?= ($block->getAttributeValidationClass('lastname') == 'required-entry') ? ' data-validate="{required:true}"' : '' ?>>
    </div>

    <?php if ($suffix) : ?>
        <div class="field field-name-suffix<?= $block->isSuffixRequired() ? ' required' : '' ?>">
            <label for="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('suffix')) ?></span></label>
            <?php if ($block->getSuffixOptions() === false) : ?>
                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                       name="<?= $block->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getObject()->getSuffix()) ?>"
                       title="<?= $block->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                    <?php if ($layout == 'customer_address_form') : ?>
                        placeholder="<?= $block->escapeHtml($block->getStoreLabel('suffix')) ?>"
                    <?php endif; ?>
                       class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>" <?= $block->isSuffixRequired() ? ' data-validate="{required:true}"' : '' ?>>
            <?php else : ?>
                <select id="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                        name="<?= $block->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                        title="<?= $block->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                        class="<?= $block->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>" <?= $block->isSuffixRequired() ? ' data-validate="{required:true}"' : '' ?>>
                    <?php if ($layout == 'customer_address_form') : ?>
                        <option value=""><?= $block->escapeHtml($block->getStoreLabel('suffix')) ?></option>
                    <?php endif; ?>
                    <?php foreach ($block->getSuffixOptions() as $_option) : ?>
                        <option value="<?= $block->escapeHtmlAttr($_option) ?>"<?php if ($block->getObject()->getSuffix() == $_option) : ?> selected="selected"<?php endif; ?>>
                            <?= $block->escapeHtml(__($_option)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
