<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Telephone $block */
    $layout   = $this->getRequest()->getFullActionName();
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <input type="text"
               name="telephone"
               id="telephone"
               maxlength="17"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               placeholder="<?= $block->escapeHtml(__('Phone Number')) ?>"
               class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('telephone')) ?: '' ?>"
        >
    </div>
</div>
