<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Existing Customer')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?= $block->escapeHtml(__("Welcome back! Enjoy the benefits of your account: faster checkout, multiple saved addresses, order tracking, and more.")) ?></p>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"  class="action create"><?= $block->escapeHtml(__('Login now')) ?></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
