<?php
/**
 * Copyright © 2018 Porto. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $block->getMenuHelper();
    $_portohelper = $block->getPortoHelper();
    
    $categories = $_helper->getFirstLevelCategories();
    $_category_config = $_portohelper->getConfig('porto_settings/category');
    $_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
    
    $aspect_ratio = $block->getData("aspect_ratio");
if ($aspect_ratio == null) {
    $aspect_ratio = $_category_config['aspect_ratio'];
}
    $ratio_width = $block->getData("image_width");
if (!$ratio_width) {
    $ratio_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
}
    $ratio_height = $block->getData("image_height");
if (!$ratio_height) {
    $ratio_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
}

    $move_actions= $block->getData("move_actions");
if (!$move_actions) {
    $move_actions = 0;
}
    $lazy_owl = $block->getData("lazy_owl");
if (!$lazy_owl) {
    $lazy_owl = 0;
}
    $product_count = $block->getData("product_count");
if (!$product_count) {
    $product_count = 12;
}
    $columns = $block->getData("columns");
if (!$columns) {
    $columns = "{0:{items:2},768:{items:3},992:{items:4},1200:{items:5}}";
}

    $product_type = $block->getData("product_type");
if ($product_type == null) {
    $product_type = $_category_grid_config['product_type'];
}
if ($product_type == null) {
    $product_type = 1;
}
    
    $custom_styles='<style type="text/css">';
?>
<div class="onepage-category">
    <div class="category-list">
        <ul>
        <?php
            $i = 0;
        foreach ($categories as $category) {
            $cat_id = $category->getId();
            $cat_model = $_helper->getCategoryModel($cat_id);
            if ($category->getIsActive() && !$cat_model->getData("sw_ocat_hide_this_item")) {
                $icon = '<em class="porto-icon-circle-empty"></em>';
                if ($cat_icon_img=$cat_model->getData("sw_ocat_category_icon_image")) {
                    $icon = '<img src="'.'catalog/category/'.$cat_icon_img.'" alt=""/>';
                } elseif ($cat_font_icon=$cat_model->getData("sw_ocat_category_font_icon")) {
                    $icon = '<em class="'.$cat_font_icon.'"></em>';
                }
                if ($hover_bg_color = $cat_model->getData("sw_ocat_category_hoverbgcolor")) {
                    $custom_styles .= '.onepage-category .category-list > ul > li > a[data-cat="'.
                    $cat_id.'"]:hover,.onepage-category .category-list > ul > li > a[data-cat="'.
                    $cat_id.'"].active{background-color:'.
                    $hover_bg_color.';}.onepage-category .category-list > ul > li > a[data-cat="'.
                    $cat_id.'"]:hover:after,.onepage-category .category-list > ul > li > a[data-cat="'.
                    $cat_id.'"].active:after{border-left-color:'.$hover_bg_color.';}';
                }
                /* @noEscape */ echo '<li data-index="'.$i.'"><a href="javascript:void(0)" data-cat="'.
                $cat_id.'">'.$icon.'<span>'.$category->getName().'</span></a></li>';
                $i++;
            }
        }
        ?>
        </ul>
        <?php
            $custom_styles .= '</style>';
            /* @noEscape */ echo $custom_styles;
        ?>
    </div>
    <div class="category-details">
    <?php
    foreach ($categories as $category) {
        $cat_id = $category->getId();
        $cat_model = $_helper->getCategoryModel($cat_id);
        if ($category->getIsActive() && !$cat_model->getData("sw_ocat_hide_this_item")) {
            $activeChildren = $_helper->getActiveChildCategories($cat_model);
            $a_class = '';
            $popup = '';
            if (count($activeChildren)) {
                $a_class = ' class="parent"';
                $popup = '<div class="menu-popup">'.$_helper->getSubmenuItemsHtml($activeChildren, 0, 2).'</div>';
            }
                
            $title_menu = '<a href="javascript:void(0)" data-id="'.$cat_id.'"'.$a_class.'><span>'.
            $cat_model->getName().'</span></a>'.$popup;
                
            $resultPage = $_helper->getResultPageFactory()->create();
            $products = $resultPage->getLayout()->createBlock(\Smartwave\Filterproducts\Block\Home\LatestList::class)
                ->setTemplate('Smartwave_Megamenu::onepagecategory/products_area.phtml')
                ->setData('category_id', $cat_id)
                ->setData('aspect_ratio', $aspect_ratio)
                ->setData('image_width', $ratio_width)
                ->setData('image_height', $ratio_height)
                ->setData('lazy_owl', $lazy_owl)
                ->setData('product_count', $product_count)
                ->setData('columns', $columns)
                ->setData('product_type', $product_type)
                ->toHtml();
                
            $additional_content = $_helper->getBlockContent($cat_model->getData("sw_ocat_additional_content"));
            ?>
        <div id="category_<?= $block->escapeHtml($cat_id); ?>" class="category-detail">
            <div class="title-menu"><?= $block->escapeHtml($title_menu); ?></div>
            <div class="products-area"><?= $block->escapeHtml($products); ?></div>
            <div class="additional-content"><?= $block->escapeHtml($additional_content); ?></div>
        </div>
            <?php
        }
    }
    ?>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "SmartwaveMegamenuOnepagecategory": {}
        }
    }
    </script>
</div>
