FROM --platform=linux/amd64 nginx:stable

COPY docker/nginx/brands-labels.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/nginx.conf.sample /etc/nginx/conf.d/nginx.conf.sample
COPY docker/nginx/nginx_usermod.sh /docker-entrypoint.d/nginx_usermod.sh
WORKDIR /var/www/magento
# COPY media.zip media.zip

RUN apt-get update -y && apt-get install -y awscli unzip

ARG S3_MEDIA_FILE_PATH
# ARG AWS_ACCESS_KEY_ENV
# ARG AWS_SECRET_ACCESS_KEY_ENV
# ARG AWS_SESSION_TOKEN_ENV

ENV S3_MEDIA_FILE_PATH=$S3_MEDIA_FILE_PATH
# ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ENV
# ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_ENV
# ENV AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_ENV

#RUN eval $AWS_ACCESS_KEY_ID && eval $AWS_SECRET_ACCESS_KEY && eval $AWS_SESSION_TOKEN 
# RUN aws s3 cp $S3_MEDIA_FILE_PATH media.zip --region us-west-2 