<?php
/** @var \Phpro\CookieConsent\ViewModel\Cookie $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="phpro-cookie-notice" style="display: none;">
    <div class="notice-wrapper">
        <div class="notice__title">
            <span><?= __('We use cookies') ?></span>
        </div>
        <div class="notice__actions">
            <div class="notice__description">
                <span><?= __('Cookies enhance your experience tailor your ads and improve our website manage') ?></span>
            </div>
            <button class="action primary notice__btn notice__btn-settings">
                <span><?= __('Necessary only') ?></span>
            </button>
            <button class="action primary notice__btn notice__btn-accept">
                <span><?= __('Accept all') ?></span>
            </button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Phpro_CookieConsent/js/notice": {
            "cookie_name": "<?= $viewModel->getCookieName(); ?>",
            "expiration": <?= $viewModel->getExpirationDays(); ?>,
            "secure": <?= $viewModel->isFrontUrlSecure(); ?>,
            "cookie_groups_data": <?= $viewModel->getGroupsData(); ?>
        }
    }
}
</script>
