<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="block <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
    <div class="title <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?= $block->escapeHtmlAttr($block->getBlockCss()) ?>", "selectorsToggleClass": "active"}}'>
        <strong>
            <?= $block->escapeHtml(__($block->getBlockTitle())) ?>
        </strong>
    </div>
    <div class="content <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-content"
         id="<?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>

<div id="modal-logout" style="display: none">
    <div class="modal-body-content">
        <p><?= $block->escapeHtml(__('Are you sure you want to log out? Logging out will terminate your current session and ensure the security of your account.')) ?></p>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Theme/js/collapsible": {
            }
        }
    }
</script>
