<?php

$dynamicHelper = $this->helper('Dynamic\Referfriend\Helper\Data');
$storeManager  = $dynamicHelper->getStoreManager();
$storeCode = $storeManager->getStore()->getCode();
$url = $storeManager->getStore()->getUrl('customer/account/login');
$siteUrl = $dynamicHelper->getScopeConfig()->getValue("web/secure/base_url");

$customerHelper = $this->helper('\Dynamic\Referfriend\Helper\Data');

$fname= '';
$email= '';
$telephone = '';
if($customerHelper->isLoggedIn()) {
    $customer = $customerHelper->getCustomerById($customerHelper->getCustomerId());
    $fname = $customer->getFirstname();
    $email = $customer->getEmail();
    if ($customerHelper->getTelephone($customer->getAddresses())) {
        $telephone = $customerHelper->getTelephone($customer->getAddresses());
    }
}

?>

<div class="cls_refer_friend_box custom_refer_section">
    <div class="cls_sub_refer_friend_box row">
        <div class="col-md-12">
            <form id="form_referbox"
                  action="<?= $block->escapeUrl($block->getUrl('referfriend/index/post')); ?>"
                  data-mage-init='{"validation": {}}'
                  class="referbox-form-custom"
                  method="POST"
                  enctype="multipart/form-data">

                    <div class="title-section">
                        <h2 class="page-sub-title"><?= /* @noEscape */ __("Refer A Friend & Earn Discounts") ?></h2>
                        <p><span class="mm-offer-text"><?= /* @noEscape */ __('Enter details below to send a ')?><span class="red"><?= /* @noEscape */ __('10% coupon code')?></span> <?= /* @noEscape */ __('to your friend') ?></span></p>
                    </div>
                    <div class="cls_referfrind_form_main">
                        <div class="cls_referfrind_form">
                            <fieldset class="fieldset refer-friend">
                                <legend class="fieldset-legend">
                                    <span><?= $block->escapeHtml(__('Refer Friend')) ?></span>
                                </legend>
                                <div class="fields">
                                    <div class="field prifix-field name required cls_comm_input">
                                        <label for="name" class="label">
                                            <span><?= /* @noEscape */ __('First Name') ?></span>
                                        </label>
                                        <div class="control prifix-input-with-option">
                                            <div class="special-number-dropdown">
                                                <select name="name_with_initials" id="initial" class="name_initial specialgender input-prefix prefix-select">
                                                    <option selected="selected" value="mr."><?= /* @noEscape */ __('Mr.'); ?></option>
                                                    <option value="mrs."><?= /* @noEscape */ __('Mrs.'); ?></option>
                                                    <option value="miss."><?= /* @noEscape */ __('Miss.'); ?></option>
                                                </select>
                                            </div>
                                            <input id="referrer_first_name" class="input-text" title="<?= /* @noEscape */ __('Your First Name') ?>"
                                                name="referrer_first_name" required="" type="text" value="<?= $block->escapeHtmlAttr($fname) ?>" placeholder="<?= /* @noEscape */ __('First Name') ?>">
                                            <div class="pwd-icon"></div>
                                        </div>
                                    </div>
                                    <div class="field prifix-field email required cls_comm_input">
                                        <label for="name" class="label">
                                            <span><?= /* @noEscape */ __('Email Address') ?></span>
                                        </label>
                                        <div class="control">
                                            <input id="referrer_email" class="input-text" title="<?= /* @noEscape */ __('Email Address') ?>"
                                                name="referrer_email" type="email" required="" value="<?= $block->escapeHtmlAttr($email) ?>" placeholder="<?= /* @noEscape */ __('Email Address') ?>">
                                            <div class="pwd-icon"></div>
                                        </div>
                                    </div>
                                </div>

                            <div class="fields">
                                <div class="field prifix-field number required cls_comm_input">
                                    <label for="name" class="label">
                                        <span><?= /* @noEscape */ __('Phone Number') ?></span>
                                    </label>
                                    <div class="control prifix-input-with-option">
                                        <div class="special-number-dropdown">
                                                <div class="selected-flag">
                                                    <i class="fi fi-in"></i>
                                                </div>
                                                <?php
                                                $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data');
                                                $defaultValue = 'IN'; // Use the country code for India as the default value
                                                ?>
                                                <?= $countryBlock->getCountryHtmlSelect($defaultValue, 'country_id', 'specialcountry', 'Country', 'class="specialcountry "'); ?>
                                         </div>
                                        <input id="referrer_phone" class="input-text" title="<?= /* @noEscape */ __('Your Phone Number') ?>"
                                            name="referrer_phone" type="text" value="<?= $block->escapeHtmlAttr($telephone) ?>" placeholder="<?= /* @noEscape */ __('Phone Number') ?>">
                                        <div class="pwd-icon"></div>
                                    </div>
                                </div>
                                <div class="field prifix-field name required cls_comm_input">
                                    <label for="name" class="label">
                                        <span><?= /* @noEscape */ __('Friend First Name') ?></span>
                                    </label>
                                    <div class="control prifix-input-with-option">
                                        <div class="special-number-dropdown">
                                            <select name="name_with_initials" id="initial" class="name_initial specialgender input-prefix prefix-select">
                                                <option selected="selected" value="mr."><?= /* @noEscape */ __('Mr.'); ?></option>
                                                <option value="mrs."><?= /* @noEscape */ __('Mrs.'); ?></option>
                                                <option value="miss."><?= /* @noEscape */ __('Miss.'); ?></option>
                                            </select>
                                       </div>
                                        <input id="yourfirstname" class="input-text" title="<?= /* @noEscape */ __('Referring Friend First Name') ?>"
                                            name="yourfirstname" required="" type="text" value="" placeholder="<?= /* @noEscape */ __('Friend First Name') ?>">
                                        <div class="pwd-icon"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="fields">
                                <div class="field email required cls_comm_input">
                                    <label for="name" class="label">
                                        <span><?= /* @noEscape */ __('Friend Email Address') ?></span>
                                    </label>
                                    <div class="control">
                                        <input id="youremailaddress" class="input-text" title="<?= /* @noEscape */ __('Referring Friend Email Address') ?>"
                                            name="youremailaddress" type="email" required="" value="" placeholder="<?= /* @noEscape */ __('Friend Email Address') ?>">
                                        <div class="pwd-icon"></div>
                                    </div>
                                </div>
                                <div class="field prifix-field number required cls_comm_input">
                                    <label for="name" class="label">
                                        <span><?= /* @noEscape */ __('Friend Phone Number') ?></span>
                                    </label>
                                    <div class="control prifix-input-with-option">
                                          <div class="special-number-dropdown">
                                                <div class="selected-flag">
                                                    <i class="fi fi-in"></i>
                                                </div>
                                                <?php
                                                $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data');
                                                $defaultValue = 'IN'; // Use the country code for India as the default value
                                                ?>
                                                <?= $countryBlock->getCountryHtmlSelect($defaultValue, 'country_id', 'specialcountry', 'Country', 'class="specialcountry"'); ?>
                                         </div>
                                         <input id="yourphonenumber" class="input-text" title="<?= /* @noEscape */ __('Referring Friend Phone Number') ?>"
                                            name="yourphonenumber" type="text" value="" placeholder="<?= /* @noEscape */ __('Friend Phone Number') ?>">
                                        <div class="pwd-icon"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </fieldset>
                    </div>

                <input id="website" class="input-text" name="website" type="hidden" value="<?= $block->escapeHtmlAttr($siteUrl) ?>">
                <input id="lang_code" class="input-text" name="lang_code" type="hidden" value="<?= $block->escapeHtmlAttr($storeCode) ?>">
                <div class="actions-toolbar">
                    <div class="primary">
                        <div class="mm-action">
                            <button id="btn_registers" class="action primary" name="ButtonRegister" type="submit">
                                <span><?= /* @noEscape */ __('Register') ?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- START RESUTLT BOX -->
            <div id="loader" style="display:none;"><?= /* @noEscape */ __('loading...'); ?></div>

            <div class="referral-modal">
                <div class="secure-modal">
                    <div id="referral-modal">
                        <div class="secure-content">
                            <div id="success-result_referbox" class="result_referbox" style="display:block;">
                                <p id="result-message"><?= /* @noEscape */ __('Thank you for your referral. Coupon Codes are sent within 60 mins. Please check your email for the referral code. In case you have not received your email please check your spam folder or contact care@brands-labels.com for further assistance.'); ?></p>
                                <div class="actions-toolbar">
                                    <div class="primary">
                                    <div class="mm-action"><button id="" class="action primary" name="ButtonRegister" type="submit"><?= /* @noEscape */ __('Refer a Friend') ?></button></div>
                                    </div>
                                </div>
                            </div>
                            <div id="failure-result_referbox" class="result_referbox" style="display:block;">
                                <p id="result-message"></p>
                            </div>
                        </div>
                    </div>
                </div>
		</div>


            <!-- END RESULT BOX -->
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Theme/js/refer-friend": {
            }
        }
    }
</script>
