<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<div class="returns-container">
    <div class="returns-left">
        <div class="returns-content-left">
            <div class="contentBlock">
                <h3><?= $block->escapeHtml(__('Return your order')) ?></h3>
                <span class="req-fields"><?= $block->escapeHtml(__('* required fields')) ?></span>
                <p style="text-align:center;"><?= $block->escapeHtml(__('Enter your order reference and email address below to see your order details. From there you can check its shipping status, cancel items or make a return.')) ?></p>
            </div>
            <div class="formBlock">

                <div class="form-control">
                    <label><?= $block->escapeHtml(__('Order reference *')) ?></label>
                    <input type="text" class="form-control">
                    <p style="font-size: 13px;
    text-align: right;margin-top:5px;"><?= $block->escapeHtml(__('How do I find my')) ?> <a href="" style="text-decoration:underline;"><?= $block->escapeHtml(__('order reference')) ?></a>?</p>
                </div>
                <div class="form-control">
                    <label><?= $block->escapeHtml(__('Email Address *')) ?></label>
                    <input type="email" class="form-control">
                </div>
                <div class="signin-link">
                    <p><?= $block->escapeHtml(__('Already a member?')) ?> <a href=""><?= $block->escapeHtml(__('Sign in')) ?></a></p>
                </div>
                <button type="submit" class="btn btn-primary return-submit"><?= $block->escapeHtml(__('Let\'s Go')) ?></button>
            </div>
        </div>
    </div>
    <div class="returns-right">
        <div class="returns-content-left">
            <div class="contentBlock">
                <h3><?= $block->escapeHtml(__('Order information goes here...')) ?></h3>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Theme/js/returns": ""
    }
}
</script>
