<?php
// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$customHeaderHelper = $this->helper('WeltPixel\CustomHeader\Helper\Data');
$searchAutoCompleteHelper = $this->helper('WeltPixel\SearchAutoComplete\Helper\Data');
$templateResultsContainer = $searchAutoCompleteHelper->getTemplateResultsContainer();
$templateResultsContainerControl = !$templateResultsContainer ? 'vertically-control' : 'horizontally-control';
$templateResultsContainer = !$templateResultsContainer ? 'vertically-black' : 'horizontally-white';
$magnifierIconIsEnabled = $customHeaderHelper->magnifierIconIsEnabled();
$placeholderText = $customHeaderHelper->getPlaceholderText();
$customHtml = $customHeaderHelper->getCustomHtml();
$serachOptionsVersion = $customHeaderHelper->getSerachOptionsVersion();
$serachOptionsVersionClass = !$serachOptionsVersion ? 'version-1' : 'version-2';
?>

<div class="wrap">
    <div id="search-mod" class="modal">
        <div class="close-sec search-visible-md">
            <a class="closebutton icon-line-cross"></a>
        </div>
        <div class="modal-content">
            <div class="block block-search wpx-block-search">
                <div class="block block-content">
                    <form class="form minisearch <?php echo $serachOptionsVersionClass;  ?>" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
                        <div class="field search wpx-pos-search">
                            <label class="label active" for="search" data-role="minisearch-label">
                                <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                            </label>
                            <div class="control <?php echo $templateResultsContainerControl; ?>">
                                <input id="search"
                                       data-mage-init='{"quickSearch":{
                                        "formSelector":"#search_mini_form",
                                        "url":"<?= /* @escapeNotVerified */ $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]) ?>",
                                        "destinationSelector":"#search_autocomplete"}
                                   }'
                                       type="text"
                                       name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                                       value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                                       placeholder="<?php echo $placeholderText; ?>"
                                       class="input-text <?php echo $templateResultsContainer; ?>"
                                       maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                                       role="combobox"
                                       aria-haspopup="false"
                                       aria-expanded="false"
                                       aria-autocomplete="both"
                                       autocomplete="off"/>

                                <div class="actions wpx-pos-search search-visible-md" <?php if($magnifierIconIsEnabled == 0) :?> style="display: none" <?php endif; ?>>
                                    <button type="submit" class="action search" title="<?= $block->escapeHtml(__('Search')) ?>"></button>
                                </div>


                                <div id="search_autocomplete" class="search-autocomplete"></div>
                                <?= $block->getChildHtml() ?>
                            </div>
                        </div>
                    </form>
                    <div class="customHtml">
                        <?php echo htmlspecialchars_decode($customHtml); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="block block-search search-visible-md minisearch-v2">
    <div class="block block-content">
        <i class="open-modal-search icon-search3"></i>
    </div>
</div>

