<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="prodBrand">
    <?php echo $product->getAttributeText('brands'); ?>
</div>
<div class="prodTitle">
    <?= $block->escapeHtml($product->getName()) ?>
</div>
