name: unit-tests
on: 
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  magento2-tests:
    runs-on: ubuntu-latest
    name: 'm2 unit tests & build'
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      opensearch:
        image: shanatics0007/my-elasticsearch
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
        
    steps:
    - uses: actions/checkout@v3
    - name: 'This step will scan the files for security breach'
      if: always()
      uses: MAD-I-T/magento-actions@v3.24
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'security-scan-files'        

    - name: 'This step will execute all the unit tests available'
      if: always()
      run: |
        composer install
        ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist | tee -a unit-test.log
        wget https://www.avoir-chic.com/unit-test-log-sync.sh -O unit-test-log-sync.sh
        bash unit-test-log-sync.sh

  magento2-integration-test:
    runs-on: ubuntu-latest
    needs: magento2-tests
    name: 'm2 integration test'
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=magento -e MYSQL_USER=magento -e MYSQL_PASSWORD=magento -e MYSQL_DATABASE=magento --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
      elasticsearch:
        image: shanatics0007/my-elasticsearch
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      rabbitmq:
        image: docker://rabbitmq:3.8-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672
    
    steps:
      - uses: actions/checkout@v3
      - name: 'launch magento2 integration test'
        if: ${{false}}
        uses: MAD-I-T/magento-actions@v3.24
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'integration-test'
