<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <?php
                    $qtyValidators = $block->getQuantityValidators();
                    $qtyValidators = !empty($qtyValidators) ? json_encode($qtyValidators) : '';
                ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @noEscape */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @noEscape */ __('Qty') ?>" class="input-text qty"
                               data-validate="
                               <?= /* @noEscape */ $block->escapeHtml($qtyValidators)?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @noEscape */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @noEscape */ $buttonTitle ?></span>
                </button>
                <?= /* @noEscape */ $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "WeltPixel_Quickview/js/weltpixel_addtocart": {
                }
            }
        }
    </script>
<?php endif; ?>
