<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Zealousweb\AppleLogin\Block\Login\Button $block */

$helper = $this->helper('\Zealousweb\AppleLogin\Helper\Data');
$buttonLabel = $helper->getButtonLabel();
$displayType = $helper->getDisplayType();
$defaultImage = $helper->getDefaultImage();
$buttonLayout = $helper->getButtonLayout();
?>
<?php if($helper->isEnabled() && !$helper->isCustomerLoggedIn()) :?>
    <div class="block block-customer-login apple-signup <?php echo (!empty($buttonLayout)) ? 'apple-btn-'.$buttonLayout: 'apple-btn-right'?>">
        <div class="space-container <?php echo (!empty($buttonLayout)) ? 'apple-icon-'.$buttonLayout: 'apple-icon-left'?>">
            <span class="space-container-inner"><span><?= $block->escapeHtml(__('Or')) ?></span></span>
        </div>
        <a href="javascript:void(0)" id="signinwithapple_login" class="action create primary signinwithapple <?php echo (!empty($displayType) && $displayType == \Zealousweb\AppleLogin\Model\Config\Source\DisplayType::DISPLAY_TYPE_BUTTON) ? '': 'login-icon';?>">
            <?php if( !empty($displayType) && $displayType == \Zealousweb\AppleLogin\Model\Config\Source\DisplayType::DISPLAY_TYPE_BUTTON ) :?>
                <span class="apple-icon">
                <?php if( !empty($helper->getButtonImage()) ) :?>
                    <?php
                    $buttonImage = 'apple/'.$helper->getButtonImage();
                    $resizeImage = $helper->getResizeImage($buttonImage, 22, 27);
                    ?>
                    <img alt="<?= $block->escapeHtml(__('Login Icon')) ?>" src="<?php echo $resizeImage; ?>">
                <?php else :?>
                    <img alt="<?= $block->escapeHtml(__('Login Icon')) ?>" src="<?php echo $defaultImage;?>">
                <?php endif;?>
            </span>
                <span class="apple-btn-text">
                <?= $buttonLabel; ?>
            </span>
            <?php else :?>
                <div class="apple-icon-inner">
                    <?php if( !empty($helper->getAppleIcon()) ) :?>
                        <?php
                        $appleIcon = 'apple/'.$helper->getAppleIcon();
                        $resizeIcon = $helper->getResizeImage($appleIcon, 90, 90);
                        ?>
                        <img alt="<?= $block->escapeHtml(__('Login Icon')) ?>" src="<?php echo $resizeIcon; ?>">
                    <?php else :?>
                        <img alt="<?= $block->escapeHtml(__('Login Icon')) ?>" src="<?php echo $defaultImage;?>">
                    <?php endif;?>
                </div>
            <?php endif;?>
        </a>
    </div>
<?php endif;?>
<div id="zealous-apple-login-button-info" data-login-url="<?php echo $helper->getAuthorizationUrl();?>"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Zealousweb_AppleLogin/js/button": {
            }
        }
    }
</script>
