<?php  /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Custom $this */ ?>

<?php $sliderConfig         = $this->getSliderConfiguration(); ?>
<?php $sliderGeneral        = $sliderConfig['slider_config']; ?>
<?php $enabled              = (array_key_exists('status', $sliderGeneral) && $sliderGeneral['status'] !=0) ? true : false; ?>
<?php $thumbsEnabled        = (array_key_exists('thumbs', $sliderGeneral) && $sliderGeneral['thumbs'] !=0) ? true : false; ?>
<?php $scheduledAjaxEnabled = (array_key_exists('scheduled_ajax', $sliderGeneral) && $sliderGeneral['scheduled_ajax'] !=0) ? true : false; ?>
<?php $thumbsArr            = [];?>

<?php if ($enabled) : ?>

    <?php
    $sliderId     = $this->getData('slider_id');
    $breakpoint   = $this->getBreakpointConfiguration();
    $bannerConfig = $sliderConfig['banner_config'];
    $sliderConfig = json_encode($sliderGeneral);
    $mediaUrl     = $this->getMediaUrl();
    $isGatEnabled = $this->isGatEnabled();
    $imageAdjustmentRequired = false;
    ?>

    <?php if ($sliderGeneral['show_title'] && trim($sliderGeneral['title'])) : ?>
        <div class="content-heading">
            <h2 class="title"><?php echo $sliderGeneral['title']; ?></h2>
        </div>
    <?php endif; ?>

    <div class="custom-slider">
        <div class="owl-carousel-custom-<?php echo $sliderId;?>" data-slider-id="<?php echo $sliderId;?>">
            <?php $ctr=0; foreach($bannerConfig as $banner) : ?>
                <?php
                    $title = (array_key_exists('title', $banner) && $banner['title'] !='') ? $banner['title'] : false;
                    $showTitle = array_key_exists('show_title', $banner) ? $banner['show_title'] : false;
                    $description = (array_key_exists('description', $banner) && $banner['description'] !='')
                        ? $banner['description'] : false;
                    $showDescription = array_key_exists('show_description', $banner)
                        ? $banner['show_description'] : false;
                    $url = array_key_exists('url', $banner) ? $banner['url'] : null;
                    $wrapLink = array_key_exists('wrap_link', $banner) ? $banner['wrap_link'] : false;
                    $target = array_key_exists('target', $banner) ? $banner['target'] : '_blank';
                    $bannerType = array_key_exists('banner_type', $banner) ? $banner['banner_type'] : '';
                    if ($bannerType == 1) {
                        $imageAdjustmentRequired = true;
                    }
                    $desktopimage = array_key_exists('image', $banner) ? $banner['image'] : '';
                    $mobileimage = array_key_exists('mobile_image', $banner) ? $banner['mobile_image'] : '';
                    $thumbimage = array_key_exists('thumb_image', $banner) ? $banner['thumb_image'] : '';

                    if(!$desktopimage && $mobileimage) $desktopimage = $mobileimage;
                    if(!$thumbimage && $desktopimage) $thumbimage = $desktopimage;

                    $altText = array_key_exists('alt_text', $banner) ? $banner['alt_text'] : '';
                    $video = array_key_exists('video', $banner) ? $banner['video'] : '';
                    $custom = array_key_exists('custom', $banner) ? $banner['custom'] : '';
                    $buttonText = array_key_exists('button_text', $banner) ? $banner['button_text'] : null;
                    $customContent = array_key_exists('custom_content', $banner) ? $banner['custom_content'] : '';
                    $customCss = array_key_exists('custom_css', $banner) ? $banner['custom_css'] : '';

                    $gaPromoId = array_key_exists('ga_promo_id', $banner) ? $banner['ga_promo_id'] : '';
                    $gaPromoName = array_key_exists('ga_promo_name', $banner) ? $banner['ga_promo_name'] : '';
                    $gaPromoCreative = array_key_exists('ga_promo_creative', $banner) ? $banner['ga_promo_creative'] : '';
                    $gaPromoPosition = array_key_exists('ga_promo_position', $banner) ? $banner['ga_promo_position'] : '';

                    $image = $desktopimage;
                    $thumbsArr[$ctr]['img'] = $thumbimage;
                    $thumbsArr[$ctr]['alt'] = $altText;
                    if ($mobileimage && $this->isMobile()) {
                        $image = $mobileimage;
                    }


					$image1 = preg_replace('"\.(bmp|gif|jpg|png)$"', '.webp', $image);

					if (@getimagesize($mediaUrl.$image1)) {
						$image = $image1;
					}
					$desktopimage1 = preg_replace('"\.(bmp|gif|jpg|png)$"', '.webp', $desktopimage);
					if (@getimagesize($mediaUrl.$desktopimage1)) {
						$desktopimage = $desktopimage1;
					}
					$mobileimage1 = preg_replace('"\.(bmp|gif|jpg|png)$"', '.webp', $mobileimage);
					if (@getimagesize($mediaUrl.$mobileimage1)) {
						$mobileimage = $mobileimage1;
					}


                ?>

                    <div class="banner-item banner-<?php echo $banner['id']; ?>">
                        <?php if ($bannerType == 1) : ?>
                            <?php if (!$buttonText): ?>
                                <?php if (isset($url)): ?>
                                    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
                                        <?php if($isGatEnabled):?>
                                            data-track-promo-id="<?php echo $gaPromoId; ?>"
                                            data-track-promo-name="<?php echo $gaPromoName; ?>"
                                            data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
                                            data-track-promo-position="<?php echo $gaPromoPosition; ?>"
                                        <?php endif;?>
                                    >
                                <?php endif; ?>
                            <?php endif; ?>

                            <span class="banner-image">
                                <img
                                    <?php if (!$sliderGeneral['lazyLoad']) : ?>
                                        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                                    <?php endif; ?>
                                    <?php if ($mobileimage) : ?>
                                        data-src-mobile="<?php echo $mediaUrl . $mobileimage ?>"
                                    <?php endif; ?>
                                    <?php if ($image) : ?>
                                        data-src-desktop="<?php echo $mediaUrl . $desktopimage ?>"
                                    <?php endif; ?>
									width="100%" height="100%"
                                    alt="<?php echo __($altText); ?>" title="<?php echo $altText; ?>" <?php echo $sliderGeneral['lazyLoad'] ? 'data-src="' . $mediaUrl . $image . '" data-src-retina="' . $mediaUrl . $image . '" class="owl-lazy"' : '' ?>
                                />

                            </span>

                            <?php if (!$buttonText): ?>
                                <?php if (isset($url)): ?>
                                    </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php elseif ($bannerType == 3) : ?>
                            <?php if (!$buttonText): ?>
                                <?php if ($url): ?>
                                    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>" >
                                <?php endif; ?>
                            <?php endif; ?>
                                <span class="banner-custom">
                                    <?php echo $custom; ?>
                                </span>
                            <?php if (!$buttonText): ?>
                                <?php if ($url): ?>
                                    </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php elseif ($bannerType == 2) : ?>
                            <span class="banner-video">
                                  <?php echo $this->getVideoHtml($video);  ?>
                            </span>
                        <?php endif; ?>
                        <?php if (isset($url)){ ?>
                          <a href="<?php echo $url; ?>" target="<?php echo $target; ?>">
                        <?php } ?>
                        <div class="content_slider test">

                            <?php if ($showTitle && $title) : ?>
                                <?php if($url != NULL): ?>
                                    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
                                        <?php if($isGatEnabled):?>
                                            data-track-promo-id="<?php echo $gaPromoId; ?>"
                                            data-track-promo-name="<?php echo $gaPromoName; ?>"
                                            data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
                                            data-track-promo-position="<?php echo $gaPromoPosition; ?>"
                                        <?php endif;?>
                                    >
                                        <span class="banner-title"><?php echo $title; ?></span>
                                    </a>
                                <?php else: ?>
                                    <span class="banner-title"><?php echo $title; ?></span>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($showDescription && $description) : ?>
                                <?php if($url != NULL): ?>
                                    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
                                        <?php if($isGatEnabled):?>
                                            data-track-promo-id="<?php echo $gaPromoId; ?>"
                                            data-track-promo-name="<?php echo $gaPromoName; ?>"
                                            data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
                                            data-track-promo-position="<?php echo $gaPromoPosition; ?>"
                                        <?php endif;?>
                                    >
                                        <span class="banner-description"><?php echo $description; ?></span>
                                    </a>
                                <?php else: ?>
                                    <span class="banner-description"><?php echo $description; ?></span>
                                <?php endif;?>
                            <?php endif; ?>

                            <div class="buttons">
                                <?php if ($customCss): ?>
                                    <style scoped>
                                        <?php echo $customCss; ?>
                                    </style>
                                <?php endif; ?>
                                <?php if ($buttonText && $url): ?>
                                    <a class="action primary" href="<?php echo $url; ?>" target="<?php echo $target; ?>"
                                        <?php if($isGatEnabled):?>
                                            data-track-promo-id="<?php echo $gaPromoId; ?>"
                                            data-track-promo-name="<?php echo $gaPromoName; ?>"
                                            data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
                                            data-track-promo-position="<?php echo $gaPromoPosition; ?>"
                                        <?php endif;?>
                                    > <?php echo $buttonText; ?> </a>
                                <?php endif; ?>
                                <?php if ($customContent): ?>
                                    <div class="clearfix"></div>
                                    <div class="custom_content">
                                        <?php if($wrapLink && $url != NULL): ?>
                                            <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
                                                <?php if($isGatEnabled):?>
                                                    data-track-promo-id="<?php echo $gaPromoId; ?>"
                                                    data-track-promo-name="<?php echo $gaPromoName; ?>"
                                                    data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
                                                    data-track-promo-position="<?php echo $gaPromoPosition; ?>"
                                                <?php endif;?>
                                            >
                                                <?php echo __($customContent); ?>
                                            </a>
                                        <?php else: ?>
                                            <?php echo __($customContent); ?>
                                        <?php endif;?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if (isset($url)){ ?>
                        </a>
                        <?php } ?>
                    </div>

            <?php $ctr++; endforeach; ?>
        </div>
        <div id="pre-div">
            <?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
            <?php if ($loaderHelper->useDefaultLoader() ) : ?>
                <div class="cssload-loader">
                    <div class="cssload-inner cssload-one"></div>
                    <div class="cssload-inner cssload-two"></div>
                    <div class="cssload-inner cssload-three"></div>
                </div>
            <?php else : ?>
                <table aria-describedby="imageloader-table" class="imageloader-loader">
                    <tbody>
                    <tr>
                        <td>
                            <img alt="<?= __('Image Loading')?>" src="<?= $loaderHelper->getLoadingImageUrl() ?>" />
                        </td>
                    </tr>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        <?php if($thumbsEnabled):?>
            <div class="owl-thumbs" data-slider-id="<?php echo $sliderId;?>">
                <?php foreach($thumbsArr as $img):?>
                    <div class="owl-thumb-item">
                        <img src="<?php echo $mediaUrl . $img['img']; ?>"
                             alt="<?php echo $img['alt']; ?>"
                             title="<?php echo $img['alt']; ?>"
                        />
                    </div>
                <?php endforeach;?>
            </div>
        <?php endif;?>
    </div>
    <?php 
    $sliderConfig =  str_replace('"', "'", $sliderConfig)
    ?>            
    <script type="text/x-magento-init">
    {
        "*": {
            "WeltPixel_OwlCarouselSlider/js/weltpixelcarousel-custom": {
                "imageAdjustmentRequired": <?= $imageAdjustmentRequired ?>,
                "sliderId": <?= $sliderId ?>,
                "sliderConfig": "<?= $sliderConfig ?>",
                "mobileBreakPoint": "<?= $this->getMobileBreakPoint() ?>",
                "breakpoint1" : <?= $breakpoint['breakpoint_1'] ?>,
                "breakpoint2" : <?= $breakpoint['breakpoint_3'] ?>,
                "breakpoint3" : <?= $breakpoint['breakpoint_3'] ?>,
                "breakpoint4" : <?= $breakpoint['breakpoint_4'] ?>
            }
        }
    }
    </script>
<?php endif; ?>
