<?php /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Products $this */ ?>

<?php $sliderData    = $this->getSliderConfiguration(); ?>
<?php $enabled       = array_key_exists('status', $sliderData) ? $sliderData['status'] : ''; ?>
<?php $showPrice     = array_key_exists('show_price', $sliderData) ? $sliderData['show_price'] : false; ?>
<?php $showAddToCart = array_key_exists('show_addto', $sliderData) ? $sliderData['show_addto'] : false; ?>
<?php $showWishlist  = (array_key_exists('show_wishlist', $sliderData) && $sliderData['show_wishlist'] !=0) ? true : false; ?>
<?php $showCompare   = (array_key_exists('show_compare', $sliderData) && $sliderData['show_compare'] !=0) ? true : false; ?>
<?php $showReviewsRatins   = (array_key_exists('show_reviews_ratings', $sliderData) && $sliderData['show_reviews_ratings'] !=0) ? true : false; ?>
<?php $randomSort = (array_key_exists('random_sort', $sliderData) && $sliderData['random_sort'] !=0) ? true : false; ?>
<?php if(!$enabled){ return; } ?>

<?php
$productsType = $this->getData('products_type');
$prCounter = 0;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

if($productsType != 'recently_viewed') {
    $products = $this->getProductCollection();
    $pageSize = count($products) < $products->getPageSize() ? count($products) : $products->getPageSize();
    if (!count($products)) {
        return;
    }
    $sliderConfig = !empty($sliderData) ? json_encode($sliderData) : '';
    $sliderTitle  = array_key_exists('title', $sliderData) ? $sliderData['title'] : '';
    $breakpoint   = $this->getBreakpointConfiguration();
    $isHoverImageEnabled = $this->isHoverImageEnabled();
    ?>

    <div class="custom-slider">
        <?php if (($sliderTitle)) : ?>
            <div class="content-heading">
                <h2 class="title"><?php echo $sliderTitle; ?></h2>
            </div>
        <?php endif; ?>
        <div class="owl-carousel-products-<?php echo $productsType;?> <?php echo count($products)== 1? 'owl-carousel-products-single-item': '';?>">
            <?php foreach($products as $product) : ?>

                <?php
                if ( $productsType == 'bestsell_products') {
                    $prCounter += 1;
                    if ($prCounter > $pageSize) {
                        break;
                    }
                }

                $productImageHoverUrl = false;
                $productImageHoverPlaceholderUrl = false;
                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                $productImageAltText = $_imagehelper->init($product, 'category_page_list')->getLabel();
                $productImage = $_imagehelper->init($product, 'category_page_list')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(480, 600)->getUrl();
                $productUrl = $product->getUrlModel()->getUrl($product);
                if ($isHoverImageEnabled) {
                    $productImageHover = $_imagehelper->init($product, 'owlcarousel_product_hover')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(480, 600);
                    $productImageHoverUrl = $productImageHover->getUrl();
                    $productImageHoverPlaceholderUrl = $productImageHover->getDefaultPlaceholderUrl();
                }
                ?>

                <div class="item product product-item">
                    <div data-container="product-grid" class="product-item-info">
                        <a tabindex="-1" class="product photo product-item-photo" href="<?php echo $productUrl; ?>">
                            <span style="width:240px;" class="product-image-container">
                                <span style="padding-bottom: 125%;" class="product-image-wrapper">
                                    <img width="240"
                                         height="300"
                                         alt="<?php echo $productImageAltText;?>"
                                        <?php if (!$sliderData['lazyLoad'] || !$sliderData['loop']) : ?>
                                            src="<?php echo $productImage; ?>"
                                        <?php endif; ?>
                                        <?php if ($isHoverImageEnabled && ($productImageHoverUrl != $productImageHoverPlaceholderUrl)) : ?>
                                            data-hoversrc="<?php /* @escapeNotVerified */ echo $productImageHoverUrl; ?>"
                                            onmouseover="if(! /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {this.setAttribute('data-tmp', this.src);this.src=this.getAttribute('data-hoversrc');}"
                                            onmouseout="if(! /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {this.src=this.getAttribute('data-tmp')}"
                                            onmousemove="if(! /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {if (this.getAttribute('data-hoversrc') != this.src) this.setAttribute('data-tmp', this.src)}"
                                        <?php endif; ?>
                                        class="product-image-photo <?php echo $sliderData['lazyLoad'] ? 'owl-lazy' : '' ?>"
                                        <?php echo $sliderData['lazyLoad'] ? 'data-src="' . $productImage . '" data-src-retina="' . $productImage . '"' : '' ?>
                                    />
                                </span>
                            </span>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a href="<?php echo $productUrl; ?>" class="product-item-link">
                                    <?php echo $product->getName(); ?>
                                </a>
                            </strong>
                            <?php if ($showReviewsRatins && $templateType): ?>
                                <?= $block->getReviewsSummaryHtml($product, $templateType) ?>
                            <?php endif; ?>
                            <?php if ($showPrice) : ?>
                                <?php /* @escapeNotVerified */ echo $this->getProductPrice($product); ?>
                            <?php endif; ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">

                                    <?php if ($showAddToCart) : ?>
                                        <div class="actions-primary">
                                            <?php if ($product->isSaleable()): ?>
                                                <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($product) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('View More') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('View More') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">

                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($product); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>

                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product);?>'
                                                       data-role="add-to-links"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div id="pre-div">
            <?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
            <?php if ($loaderHelper->useDefaultLoader() ) : ?>
            <div class="cssload-loader">
                <div class="cssload-inner cssload-one"></div>
                <div class="cssload-inner cssload-two"></div>
                <div class="cssload-inner cssload-three"></div>
            </div>
            <?php else : ?>
                <table aria-describedby="imageloader-table" class="imageloader-loader">
                    <tbody>
                        <tr>
                            <td>
                                <img alt="<?= __('Image Loading')?>" src="<?= $loaderHelper->getLoadingImageUrl() ?>" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </div>
    <?php
        $sliderConfig = !empty($sliderConfig) ? str_replace('"', "'", $sliderConfig) : '';
    ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "WeltPixel_OwlCarouselSlider/js/weltpixelcarousel-products": {
                "productsType": "<?php echo $productsType; ?>",
                "productsCount": "<?php echo count($products) ?>",
                "randomSort": "<?= $randomSort ?>",
                "breakpoint1" : <?= $breakpoint['breakpoint_1'] ?>,
                "breakpoint2" : <?= $breakpoint['breakpoint_3'] ?>,
                "breakpoint3" : <?= $breakpoint['breakpoint_3'] ?>,
                "breakpoint4" : <?= $breakpoint['breakpoint_4'] ?>,
                "sliderConfig" : "<?= $sliderConfig ?>"
            }
        }
    }
    </script>
<?php
} else {
?>
    <div id="recently_viewed"></div>

    <script type="text/x-magento-init">
    {
        "#recently_viewed": {
            "owlAjax": {
                "ajaxUrl": "<?php echo $block->getUrl('ajaxowl/recentlyviewed/index') ?>",
                "requestType": "recently_viewed"
            }
        }

    }
    </script>
<?php
}
?>


